{
 "title": "Alluxio-Prometheus-Grafana-Monitor-New",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alluxio_datasource",
    "label": "The datasource of alluxio prometheus",
    "query": "prometheus"
   },
   {
    "name": "masters",
    "label": "The prometheus job_name including master nodes",
    "query": "alluxio master"
   },
   {
    "name": "workers",
    "label": "The prometheus job_name including worker nodes",
    "query": "alluxio worker"
   },
   { "name": "alluxio_user", "label": "The super user of alluxio", "query": "root" },
   { "name": "job_masters", "query": "alluxio job master" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "cluster_name", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lost Workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_LostWorkers{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Live Workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_Workers{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "description": "Cache hit rate: (# bytes read from cache) / (# bytes requested)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "Cluster_CacheHitRate{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Cluster Cache Hit Rate"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "% Alluxio Space Used",
   "type": "graph",
   "description": "The percentage of use space",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(Cluster_CapacityUsed{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}) / (Cluster_CapacityTotal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Alluxio Space Used"
    }
   ]
  },
  {
   "title": "% UFS Space Used",
   "type": "graph",
   "description": "The percent of Ufs space used",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "Cluster_RootUfsCapacityUsed{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}/Cluster_RootUfsCapacityTotal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "UFS Space Used"
    }
   ]
  },
  {
   "title": "Alluxio Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_CapacityTotal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Cluster_CapacityTotal"
    },
    {
     "expr": "Cluster_CapacityUsed{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Cluster Capacity Used"
    }
   ]
  },
  {
   "title": "UFS Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_RootUfsCapacityTotal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Cluster Root Ufs Capacity Total"
    },
    {
     "expr": "Cluster_RootUfsCapacityUsed{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Cluster Root Ufs Capacity Used"
    }
   ]
  },
  { "title": "Alluxio Metadata Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Block Heartbeat Operation",
   "type": "graph",
   "description": "Displays the 50th, 95th, and 99th percentiles call time for the blockHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Block Heartbeat just how long it took the operation to run",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"$masters\",quantile=\"0.5\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Block Heartbeat:0.5"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"$masters\",quantile=\"0.95\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Block Heartbeat:0.95"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"$masters\",quantile=\"0.99\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Block Heartbeat:0.99"
    }
   ]
  },
  {
   "title": "Get Configuration Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\",quantile=\"0.99\"}"
    }
   ]
  },
  { "title": "Alluxio IO Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Read IO Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Cluster_BytesReadLocal{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Read Local"
    },
    {
     "expr": "Cluster_BytesReadRemote{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Read Remote"
    },
    {
     "expr": "Cluster_BytesReadUfsAll{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Read Ufs"
    },
    {
     "expr": "Cluster_BytesReadDomain{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Read Domain"
    }
   ]
  },
  {
   "title": "Write IO Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_BytesWrittenLocal{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Written Local"
    },
    {
     "expr": "Cluster_BytesWrittenRemote{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Written Remote"
    },
    {
     "expr": "Cluster_BytesWrittenUfsAll{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Written Ufs"
    },
    {
     "expr": "Cluster_BytesWrittenDomain{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Written Domain"
    }
   ]
  },
  {
   "title": "Bytes Read Local (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesReadLocal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Read Local (Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Read Remote (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesReadRemote{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Read Remote(Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Read Domain (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesReadDomain{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Read Domain (Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Read UFS (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesReadUfsAll{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Read UFS (Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Read Local",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadLocal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Read Local"
    }
   ]
  },
  {
   "title": "Bytes Read Remote ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadRemote{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Read Remote "
    }
   ]
  },
  {
   "title": "Bytes Written Local (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesWrittenLocal{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Written UFS (Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Written Remote (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesWrittenRemote{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Written Remote (Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Written Domain (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesWrittenDomain{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Written Domain(Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Written UFS (Per Sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(Cluster_BytesWrittenUfsAll{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Bytes Written UFS (Per Sec)"
    }
   ]
  },
  {
   "title": "Bytes Written Local",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Cluster_BytesWrittenLocal{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Written Local"
    }
   ]
  },
  {
   "title": "Bytes Written Remote",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Cluster_BytesWrittenRemote{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Bytes Written Remote"
    }
   ]
  },
  { "title": "Logical Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Directories Created",
   "type": "stat",
   "description": "Displays the current number of how many directories Alluxio has created since starting",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_DirectoriesCreated{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "stat",
   "description": "displays the number of times the FileInfosGot operation was called",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FileInfosGot{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "stat",
   "description": "Displays the total paths located in the Alluxio file system",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_TotalPaths{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Complete File Operations",
   "type": "stat",
   "description": "Displays how many times the CompleteFile operation has been called",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_CompleteFileOps{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Create Directory Oprtations",
   "type": "stat",
   "description": "Displays the amount of directories that Alluxio has created (Not the current amount of directories)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_CreateDirectoryOps{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "stat",
   "description": "Displays how many times the deletePath operation has been called (And how many total paths have been deleted)",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_DeletePathOps{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "FilesCreated",
   "type": "stat",
   "description": "Displays how many times the deletePath operation has been called (And how many total paths have been deleted)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesCreated{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "stat",
   "description": "Displays the current number of pinned files in Alluxio",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesPinned{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Mount Operations",
   "type": "stat",
   "description": "Displays how many times the mount operation has been called (including failed invocations)",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_MountOps{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Files Freed",
   "type": "stat",
   "description": "Displays the current number of freed files in Alluxio",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesFreed{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Unmount Operations",
   "type": "stat",
   "description": "Displays how many times the unmount operation has been called",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_UnmountOps{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  { "title": "Alluxio Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  { "title": "Master Rpc Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Master_TotalRpcs time",
   "type": "timeseries",
   "description": "Throughput of master RPC calls. This metrics indicates how busy the master is serving client and worker requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Master_TotalRpcs{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Master TotalRpcs Count (Per Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "rate(Master_TotalRpcs_count{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "Master TotalRpcs Count"
    }
   ]
  },
  {
   "title": "Master_RpcQueueLength",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "Master_RpcQueueLength{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "RpcQueueLength"
    }
   ]
  },
  { "title": "Master Meta Cache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Master_InodeHeapSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Master_InodeHeapSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Master_InodeHeapSize"
    }
   ]
  },
  {
   "title": "LockPoolSize",
   "type": "timeseries",
   "description": "The size of master inode lock pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "Master_InodeLockPoolSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Master_InodeLockPoolSize"
    },
    {
     "expr": "Master_EdgeLockPoolSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Master_EdgeLockPoolSize"
    }
   ]
  },
  {
   "title": "Inode Heap SIze",
   "type": "stat",
   "description": "An estimate of the inode heap size",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_InodeHeapSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Inode Heap Size"
    }
   ]
  },
  {
   "title": "Master Cache Hit Rate",
   "type": "gauge",
   "description": "The master meta cache hits rate, include edge cache, inode cache and list cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_EdgeCacheHits{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}/(Master_EdgeCacheMisses + Master_EdgeCacheHits{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Master Edge Cache Rate"
    },
    {
     "expr": "Master_InodeCacheHits{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}/(Master_InodeCacheMisses + Master_InodeCacheHits{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Master Inode Cache Rate"
    },
    {
     "expr": "Master_ListingCacheHits{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}/(Master_ListingCacheMisses + Master_ListingCacheHits{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Master Listing Cache Rate"
    }
   ]
  },
  {
   "title": "Master Meta Cache Size",
   "type": "stat",
   "description": "The master meta cache size, include edge, inode, and llist.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_InodeCacheSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Inode Cache Size"
    },
    {
     "expr": "Master_EdgeCacheSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Edge Cache Size"
    },
    {
     "expr": "Master_ListingCacheSize{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Listing Cache Size"
    }
   ]
  },
  { "title": "Master Block Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Master Replica Actove Job Size",
   "type": "timeseries",
   "description": "Number of active block replication/eviction jobs. These jobs are created by the master to maintain the block replica factor. The value is an estimate with lag.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "Master_ReplicaMgmtActiveJobSize{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Total Block Count ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_BlockReplicaCount{namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Lost Block Count",
   "type": "stat",
   "description": "Count of lost unique blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_LostBlockCount{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Unique Block Count",
   "type": "stat",
   "description": "Total number of unique blocks in Alluxio",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_UniqueBlocks{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  { "title": "Master File Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "title": "Master Total Path",
   "type": "stat",
   "description": "Total number of files and directory in Alluxio namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_TotalPaths{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Master Lost File Count",
   "type": "stat",
   "description": "Count of lost files. This number is cached and may not be in sync with {lost count} ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_LostFileCount{job=\"alluxio master\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}"
    }
   ]
  },
  { "title": "Master Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Master count",
   "type": "timeseries",
   "description": "Represents the current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Master Thread Info",
   "type": "timeseries",
   "description": "JVM中处于TERMINATED状态的线程数量\nJVM中处于TIMED_WAITING状态的线程数量\nJVM中处于WAITING状态的线程数量\nJVM中处于RUNNABLE状态的线程数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 177 },
   "targets": [
    {
     "expr": "blocked_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "blocked_count"
    },
    {
     "expr": "terminated_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "terminated_count"
    },
    {
     "expr": "runnable_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "runnable_count"
    },
    {
     "expr": "timed_waiting_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "timed_waiting_count"
    },
    {
     "expr": "daemon_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "daemon_count"
    },
    {
     "expr": "new_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "new_count"
    },
    {
     "expr": "deadlock_count{job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "dead_count"
    }
   ]
  },
  { "title": "Master JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Master Pools Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Metaspace_used\", job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools_Metaspace_used"
    },
    {
     "expr": "{__name__=\"pools_G1_Old_Gen_used\", job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools_G1_Old_Gen_used"
    },
    {
     "expr": "{__name__=\"pools_G1_Survivor_Space_used_after_gc\", job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools_G1_Survivor_Space_used_after_gc"
    },
    {
     "expr": "{__name__=\"pools_G1_Eden_Space_usage\", job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools_G1_Eden_Space_usage"
    },
    {
     "expr": "{__name__=\"pools_G1_Old_Gen_used\", job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools_G1_Old_Gen_used"
    }
   ]
  },
  {
   "title": "Master Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 187 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"heap_used\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "heap_used"
    },
    {
     "expr": "{__name__=\"heap_max\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "heap_max"
    },
    {
     "expr": "{__name__=\"non_heap_used\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "non_heap_used"
    }
   ]
  },
  {
   "title": "Master Total Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 187 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"total_max\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "total_max"
    },
    {
     "expr": "{__name__=\"total_used\",job=\"$masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "total_used"
    }
   ]
  },
  { "title": "Alluxio Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "Worker Active Client",
   "type": "timeseries",
   "description": "The number of clients actively reading from or writing to this worker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "targets": [
    {
     "expr": "rate({__name__=~\"Worker_ActiveClients.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Rpc Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_RpcQueueLength.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Worker Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 } },
  {
   "title": "% Worker Space Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 206 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityUsed_.*\",job=\"$workers\"}/{__name__=~\"Worker_CapacityTotal_.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Space Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityTotal_.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Space Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityTotal_.*\",job=\"$workers\"}-{__name__=~\"Worker_CapacityUsed_.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Space Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityUsed_.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Workers Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Cached Blocks ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksCached.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Deleted Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksDeleted.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Lost Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksLost.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Evicted Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksEvicted.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CacheSuccessedBlocks (Per Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"Worker_CacheSucceededBlocks.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CacheFailedBlocks (Per Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"Worker_CacheFailedBlocks.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CacheRemoteBlocks (Per Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"Worker_CacheRemoteBlocks.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CacheUfsBlocks (Per Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"Worker_CacheUfsBlocks.*\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Worker Block Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 235 } },
  {
   "title": "Worker Reader Busy Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 236 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockReaderThreadActiveCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}/{__name__=~\"Worker_BlockReaderThreadMaxCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Writer Busy Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 236 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockWriterThreadActiveCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}/{__name__=~\"Worker_BlockWriterThreadMaxCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Block Writer Thread Max",
   "type": "timeseries",
   "description": "The maximum allowed number of block read thread in the reader thread pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 245 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockWriterThreadMaxCount.*\", job=\"alluxio worker\", namespace=~\"$namespace\", cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Block Reader Thread Max",
   "type": "timeseries",
   "description": "The maximum allowed number of block read thread in the reader thread pool",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 245 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockReaderThreadMaxCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Block Reader  Active Thread Count",
   "type": "timeseries",
   "description": "The approximate number of block read threads, that are actively executing tasks in reader thread pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 245 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockReaderThreadActiveCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Block Writer Active Thread Count",
   "type": "timeseries",
   "description": "The approximate number of block read threads, that are actively executing tasks in reader thread pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 252 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockWriterThreadActiveCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Block Reader Current Thread Count",
   "type": "timeseries",
   "description": "The current number of read threads in the reader thread pool",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 252 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockReaderThreadCurrentCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Block Writer Current Thread Count",
   "type": "timeseries",
   "description": "The current number of read threads in the reader thread pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 252 },
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlockWriterThreadCurrentCount.*\", job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Worker JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 259 } },
  {
   "title": "Worker Heap Memory Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "heap_max{job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "heap_used{job=\"alluxio worker\", namespace=~\"$namespace\", cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Total Memory Max",
   "type": "timeseries",
   "description": "The worker total memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=\"total_max\",job=\"$workers\", namespace=~\"$namespace\", cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Total Memory Used",
   "type": "timeseries",
   "description": "The total memory used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=\"total_used\",job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Pools Compressed Class Space Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Compressed_Class_Space_used\", job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Pools Metaspace Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 276 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Metaspace_used\", job=\"$workers\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Pools G1 Old Gen Max Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 283 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_G1_Old_Gen_max{job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker Pools G1 Old Gen Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 283 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pools_G1_Old_Gen_used{job=\"alluxio worker\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Alluxio Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 290 } },
  { "title": "Job Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 291 } },
  {
   "title": "Job Created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 292 },
   "targets": [
    {
     "expr": "JobMaster_Master_JobCreated{job=\"$job_masters\", namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Job Create"
    }
   ]
  },
  {
   "title": "Job Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 292 },
   "targets": [
    {
     "expr": "JobMaster_Master_JobCompleted{job=\"$job_masters\", namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Job Count"
    }
   ]
  },
  {
   "title": "Job Running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 299 },
   "targets": [
    {
     "expr": "JobMaster_Master_JobRunning{job=\"$job_masters\", namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Job Running "
    }
   ]
  },
  {
   "title": "Job Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 299 },
   "targets": [
    {
     "expr": "JobMaster_Master_JobFailed{job=\"$job_masters\", namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Job Failed"
    }
   ]
  },
  { "title": "JobMaster Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 306 } },
  {
   "title": "JobMaster thread info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 307 },
   "targets": [
    {
     "expr": "blocked_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "blocked_count"
    },
    {
     "expr": "terminated_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "terminated_count"
    },
    {
     "expr": "runnable_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "runnable_count"
    },
    {
     "expr": "timed_waiting_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "timed_waiting_count"
    },
    {
     "expr": "daemon_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "daemon_count"
    }
   ]
  },
  {
   "title": "JobMaster New Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 307 },
   "targets": [
    {
     "expr": "new_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "new_count"
    }
   ]
  },
  {
   "title": "JobMaster Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 307 },
   "targets": [
    {
     "expr": "count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "JobMaster deadlock count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 307 },
   "targets": [
    {
     "expr": "deadlock_count{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "deadlock_count"
    }
   ]
  },
  {
   "title": "JobMaster Loaded",
   "type": "graph",
   "description": "Class loaded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 316 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "loaded{job=\"$job_masters\", namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "JobMaster Unloaded",
   "type": "graph",
   "description": "Class unloaded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 316 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "unloaded{job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  { "title": "JobMaster JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 324 } },
  {
   "title": "JobMaster Memory",
   "type": "graph",
   "description": "Job Master total memory and total used memory",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 325 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"total_max\",job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "total_max"
    },
    {
     "expr": "{__name__=\"total_used\",job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "total_used"
    }
   ]
  },
  {
   "title": "JobMaster Heap Memory",
   "type": "graph",
   "description": "Job Master heap total memory and heap used memory",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 325 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"heap_used\",job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "heap_used"
    },
    {
     "expr": "{__name__=\"heap_max\",job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "heap_max"
    },
    {
     "expr": "{__name__=\"non_heap_used\",job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "non_heap_used"
    }
   ]
  },
  {
   "title": "JobMaster Pools Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 325 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Compressed_Class_Space_used\", job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools Compressed Class Space used"
    },
    {
     "expr": "{__name__=\"pools_Metaspace_used\", job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools Metaspace used"
    },
    {
     "expr": "{__name__=\"pools_PS_Eden_Space_used\", job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools PS Eden Space used"
    },
    {
     "expr": "{__name__=\"pools_PS_Survivor_Space_used\", job=\"$job_masters\",namespace=~\"$namespace\",cluster_name=~\"$cluster_name\"}",
     "legendFormat": "pools PS Survivor Space_used"
    }
   ]
  }
 ]
}