// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public final class FileSystemMasterProto {
  private FileSystemMasterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CheckConsistencyPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CheckConsistencyPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CheckConsistencyPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CheckConsistencyPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CheckConsistencyPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CheckConsistencyPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CompleteFilePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CompleteFilePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CompleteFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CompleteFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CompleteFilePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CompleteFilePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_OpenFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_OpenFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateDirectoryPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateDirectoryPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateDirectoryPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateDirectoryPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateDirectoryPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateDirectoryPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateFilePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateFilePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateFilePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateFilePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DeletePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DeletePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DeletePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DeletePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DeletePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DeletePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FreePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FreePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FreePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FreePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FreePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FreePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetStatusPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetStatusPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetStatusPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetStatusPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetStatusPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetStatusPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ExistsPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ExistsPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SyncPointInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SyncPointInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetSyncPathListPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetSyncPathListPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetSyncPathListPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetSyncPathListPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ListStatusPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ListStatusPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ListStatusPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ListStatusPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ListStatusPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ListStatusPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_LoadMetadataPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_LoadMetadataPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_LoadMetadataPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_LoadMetadataPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_LoadMetadataPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_LoadMetadataPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PAclEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PAclEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PAcl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PAcl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileBlockInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileBlockInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetMountTablePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetMountTablePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetMountTablePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPointInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPointInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemCommandOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemCommandOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PersistCommandOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PersistCommandOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PersistFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PersistFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenamePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenamePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenamePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenamePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenamePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenamePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAttributePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAttributePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAttributePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAttributePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAttributePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAttributePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAclPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAclPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAclPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAclPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAclPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAclPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StartSyncPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StartSyncPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StartSyncPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StartSyncPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StartSyncPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StartSyncPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StopSyncPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StopSyncPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StopSyncPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StopSyncPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StopSyncPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StopSyncPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UnmountPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UnmountPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UnmountPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UnmountPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UnmountPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UnmountPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UfsInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UfsInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UpdateUfsModePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UpdateUfsModePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UpdateUfsModePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UpdateUfsModePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UpdateUfsModePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UpdateUfsModePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetFileInfoPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetFileInfoPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetFileInfoPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetFileInfoPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetFileInfoPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetFileInfoPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetUfsInfoPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetUfsInfoPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetUfsInfoPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetUfsInfoPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetUfsInfoPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetUfsInfoPRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035grpc/file_system_master.proto\022\021alluxio" +
      ".grpc.file\032\021grpc/common.proto\032\023grpc/fsco" +
      "mmon.proto\"q\n\036FileSystemMasterCommonPOpt" +
      "ions\022\026\n\016syncIntervalMs\030\001 \001(\003\022\013\n\003ttl\030\002 \001(" +
      "\003\022*\n\tttlAction\030\003 \001(\0162\027.alluxio.grpc.TtlA" +
      "ction\"6\n\031CheckConsistencyPResponse\022\031\n\021in" +
      "consistentPaths\030\001 \003(\t\"d\n\030CheckConsistenc" +
      "yPOptions\022H\n\rcommonOptions\030\001 \001(\01321.allux" +
      "io.grpc.file.FileSystemMasterCommonPOpti" +
      "ons\"f\n\030CheckConsistencyPRequest\022\014\n\004path\030" +
      "\001 \001(\t\022<\n\007options\030\002 \001(\0132+.alluxio.grpc.fi" +
      "le.CheckConsistencyPOptions\"\027\n\025CompleteF" +
      "ilePResponse\"s\n\024CompleteFilePOptions\022\021\n\t" +
      "ufsLength\030\001 \001(\003\022H\n\rcommonOptions\030\002 \001(\01321" +
      ".alluxio.grpc.file.FileSystemMasterCommo" +
      "nPOptions\"^\n\024CompleteFilePRequest\022\014\n\004pat" +
      "h\030\001 \001(\t\0228\n\007options\030\002 \001(\0132\'.alluxio.grpc." +
      "file.CompleteFilePOptions\"\352\001\n\020OpenFilePO" +
      "ptions\022.\n\010readType\030\001 \001(\0162\034.alluxio.grpc." +
      "file.ReadPType\022\035\n\025maxUfsReadConcurrency\030" +
      "\002 \001(\005\022\036\n\026fileReadLocationPolicy\030\003 \001(\t\022\035\n" +
      "\025hashingNumberOfShards\030\004 \001(\005\022H\n\rcommonOp" +
      "tions\030\005 \001(\01321.alluxio.grpc.file.FileSyst" +
      "emMasterCommonPOptions\"\032\n\030CreateDirector" +
      "yPResponse\"\313\001\n\027CreateDirectoryPOptions\022\021" +
      "\n\trecursive\030\001 \001(\010\022\023\n\013allowExists\030\002 \001(\010\022\014" +
      "\n\004mode\030\003 \001(\005\0220\n\twriteType\030\004 \001(\0162\035.alluxi" +
      "o.grpc.file.WritePType\022H\n\rcommonOptions\030" +
      "\005 \001(\01321.alluxio.grpc.file.FileSystemMast" +
      "erCommonPOptions\"d\n\027CreateDirectoryPRequ" +
      "est\022\014\n\004path\030\001 \001(\t\022;\n\007options\030\002 \001(\0132*.all" +
      "uxio.grpc.file.CreateDirectoryPOptions\"\025" +
      "\n\023CreateFilePResponse\"\311\002\n\022CreateFilePOpt" +
      "ions\022\026\n\016blockSizeBytes\030\001 \001(\003\022\021\n\trecursiv" +
      "e\030\002 \001(\010\022\014\n\004mode\030\003 \001(\005\022\026\n\016replicationMax\030" +
      "\004 \001(\005\022\026\n\016replicationMin\030\005 \001(\005\022\032\n\022replica" +
      "tionDurable\030\006 \001(\005\022\037\n\027fileWriteLocationPo" +
      "licy\030\007 \001(\t\022\021\n\twriteTier\030\010 \001(\005\0220\n\twriteTy" +
      "pe\030\t \001(\0162\035.alluxio.grpc.file.WritePType\022" +
      "H\n\rcommonOptions\030\n \001(\01321.alluxio.grpc.fi" +
      "le.FileSystemMasterCommonPOptions\"Z\n\022Cre" +
      "ateFilePRequest\022\014\n\004path\030\001 \001(\t\0226\n\007options" +
      "\030\002 \001(\0132%.alluxio.grpc.file.CreateFilePOp" +
      "tions\"\021\n\017DeletePResponse\"\225\001\n\016DeletePOpti" +
      "ons\022\021\n\trecursive\030\001 \001(\010\022\023\n\013alluxioOnly\030\002 " +
      "\001(\010\022\021\n\tunchecked\030\003 \001(\010\022H\n\rcommonOptions\030" +
      "\004 \001(\01321.alluxio.grpc.file.FileSystemMast" +
      "erCommonPOptions\"R\n\016DeletePRequest\022\014\n\004pa" +
      "th\030\001 \001(\t\0222\n\007options\030\002 \001(\0132!.alluxio.grpc" +
      ".file.DeletePOptions\"\017\n\rFreePResponse\"{\n" +
      "\014FreePOptions\022\021\n\trecursive\030\001 \001(\010\022\016\n\006forc" +
      "ed\030\002 \001(\010\022H\n\rcommonOptions\030\003 \001(\01321.alluxi" +
      "o.grpc.file.FileSystemMasterCommonPOptio" +
      "ns\"N\n\014FreePRequest\022\014\n\004path\030\001 \001(\t\0220\n\007opti" +
      "ons\030\002 \001(\0132\037.alluxio.grpc.file.FreePOptio" +
      "ns\"+\n\035GetNewBlockIdForFilePResponse\022\n\n\002i" +
      "d\030\001 \001(\003\"h\n\034GetNewBlockIdForFilePOptions\022" +
      "H\n\rcommonOptions\030\001 \001(\01321.alluxio.grpc.fi" +
      "le.FileSystemMasterCommonPOptions\"n\n\034Get" +
      "NewBlockIdForFilePRequest\022\014\n\004path\030\001 \001(\t\022" +
      "@\n\007options\030\002 \001(\0132/.alluxio.grpc.file.Get" +
      "NewBlockIdForFilePOptions\"C\n\022GetStatusPR" +
      "esponse\022-\n\010fileInfo\030\001 \001(\0132\033.alluxio.grpc" +
      ".file.FileInfo\"\235\001\n\021GetStatusPOptions\022>\n\020" +
      "loadMetadataType\030\001 \001(\0162$.alluxio.grpc.fi" +
      "le.LoadMetadataPType\022H\n\rcommonOptions\030\002 " +
      "\001(\01321.alluxio.grpc.file.FileSystemMaster" +
      "CommonPOptions\"X\n\021GetStatusPRequest\022\014\n\004p" +
      "ath\030\001 \001(\t\0225\n\007options\030\002 \001(\0132$.alluxio.grp" +
      "c.file.GetStatusPOptions\"\232\001\n\016ExistsPOpti" +
      "ons\022>\n\020loadMetadataType\030\001 \001(\0162$.alluxio." +
      "grpc.file.LoadMetadataPType\022H\n\rcommonOpt" +
      "ions\030\002 \001(\01321.alluxio.grpc.file.FileSyste" +
      "mMasterCommonPOptions\"]\n\rSyncPointInfo\022\024" +
      "\n\014syncPointUri\030\001 \001(\t\0226\n\nsyncStatus\030\002 \001(\016" +
      "2\".alluxio.grpc.file.SyncPointStatus\"O\n\030" +
      "GetSyncPathListPResponse\0223\n\tsyncPaths\030\001 " +
      "\003(\0132 .alluxio.grpc.file.SyncPointInfo\"\031\n" +
      "\027GetSyncPathListPRequest\"E\n\023ListStatusPR" +
      "esponse\022.\n\tfileInfos\030\001 \003(\0132\033.alluxio.grp" +
      "c.file.FileInfo\"\315\001\n\022ListStatusPOptions\022\032" +
      "\n\022loadDirectChildren\030\001 \001(\010\022>\n\020loadMetada" +
      "taType\030\002 \001(\0162$.alluxio.grpc.file.LoadMet" +
      "adataPType\022H\n\rcommonOptions\030\003 \001(\01321.allu" +
      "xio.grpc.file.FileSystemMasterCommonPOpt" +
      "ions\022\021\n\trecursive\030\004 \001(\010\"Z\n\022ListStatusPRe" +
      "quest\022\014\n\004path\030\001 \001(\t\0226\n\007options\030\002 \001(\0132%.a" +
      "lluxio.grpc.file.ListStatusPOptions\"#\n\025L" +
      "oadMetadataPResponse\022\n\n\002id\030\001 \001(\003\"\324\001\n\024Loa" +
      "dMetadataPOptions\022\021\n\trecursive\030\001 \001(\010\022\027\n\017" +
      "createAncestors\030\002 \001(\010\022F\n\022loadDescendantT" +
      "ype\030\003 \001(\0162*.alluxio.grpc.fscommon.LoadDe" +
      "scendantPType\022H\n\rcommonOptions\030\004 \001(\01321.a" +
      "lluxio.grpc.file.FileSystemMasterCommonP" +
      "Options\"a\n\024LoadMetadataPRequest\022\017\n\007ufsPa" +
      "th\030\001 \001(\t\0228\n\007options\030\002 \001(\0132\'.alluxio.grpc" +
      ".file.LoadMetadataPOptions\"\217\001\n\tPAclEntry" +
      "\022.\n\004type\030\001 \001(\0162 .alluxio.grpc.file.PAclE" +
      "ntryType\022\017\n\007subject\030\002 \001(\t\022.\n\007actions\030\003 \003" +
      "(\0162\035.alluxio.grpc.file.PAclAction\022\021\n\tisD" +
      "efault\030\004 \001(\010\"\222\001\n\004PAcl\022\r\n\005owner\030\001 \001(\t\022\023\n\013" +
      "owningGroup\030\002 \001(\t\022-\n\007entries\030\003 \003(\0132\034.all" +
      "uxio.grpc.file.PAclEntry\022\014\n\004mode\030\004 \001(\005\022\021" +
      "\n\tisDefault\030\005 \001(\010\022\026\n\016isDefaultEmpty\030\006 \001(" +
      "\010\"\235\001\n\rFileBlockInfo\022*\n\tblockInfo\030\001 \001(\0132\027" +
      ".alluxio.grpc.BlockInfo\022\016\n\006offset\030\002 \001(\003\022" +
      "4\n\014ufsLocations\030\003 \003(\0132\036.alluxio.grpc.Wor" +
      "kerNetAddress\022\032\n\022ufsStringLocations\030\004 \003(" +
      "\t\"\304\005\n\010FileInfo\022\016\n\006fileId\030\001 \001(\003\022\014\n\004name\030\002" +
      " \001(\t\022\014\n\004path\030\003 \001(\t\022\017\n\007ufsPath\030\004 \001(\t\022\016\n\006l" +
      "ength\030\005 \001(\003\022\026\n\016blockSizeBytes\030\006 \001(\003\022\026\n\016c" +
      "reationTimeMs\030\007 \001(\003\022\021\n\tcompleted\030\010 \001(\010\022\016" +
      "\n\006folder\030\t \001(\010\022\016\n\006pinned\030\n \001(\010\022\021\n\tcachea" +
      "ble\030\013 \001(\010\022\021\n\tpersisted\030\014 \001(\010\022\020\n\010blockIds" +
      "\030\r \003(\003\022\036\n\026lastModificationTimeMs\030\016 \001(\003\022\013" +
      "\n\003ttl\030\017 \001(\003\022\r\n\005owner\030\020 \001(\t\022\r\n\005group\030\021 \001(" +
      "\t\022\014\n\004mode\030\022 \001(\005\022\030\n\020persistenceState\030\023 \001(" +
      "\t\022\022\n\nmountPoint\030\024 \001(\010\0228\n\016fileBlockInfos\030" +
      "\025 \003(\0132 .alluxio.grpc.file.FileBlockInfo\022" +
      "*\n\tttlAction\030\026 \001(\0162\027.alluxio.grpc.TtlAct" +
      "ion\022\017\n\007mountId\030\027 \001(\003\022\033\n\023inAlluxioPercent" +
      "age\030\030 \001(\005\022\032\n\022inMemoryPercentage\030\031 \001(\005\022\026\n" +
      "\016ufsFingerprint\030\032 \001(\t\022$\n\003acl\030\033 \001(\0132\027.all" +
      "uxio.grpc.file.PAcl\022+\n\ndefaultAcl\030\034 \001(\0132" +
      "\027.alluxio.grpc.file.PAcl\022\026\n\016replicationM" +
      "ax\030\035 \001(\005\022\026\n\016replicationMin\030\036 \001(\005\"\020\n\016Moun" +
      "tPResponse\"\364\001\n\rMountPOptions\022\020\n\010readOnly" +
      "\030\001 \001(\010\022D\n\nproperties\030\002 \003(\01320.alluxio.grp" +
      "c.file.MountPOptions.PropertiesEntry\022\016\n\006" +
      "shared\030\003 \001(\010\022H\n\rcommonOptions\030\004 \001(\01321.al" +
      "luxio.grpc.file.FileSystemMasterCommonPO" +
      "ptions\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001\"h\n\rMountPRequest\022\023\n\013al" +
      "luxioPath\030\001 \001(\t\022\017\n\007ufsPath\030\002 \001(\t\0221\n\007opti" +
      "ons\030\003 \001(\0132 .alluxio.grpc.file.MountPOpti" +
      "ons\"\300\001\n\026GetMountTablePResponse\022O\n\013mountP" +
      "oints\030\001 \003(\0132:.alluxio.grpc.file.GetMount" +
      "TablePResponse.MountPointsEntry\032U\n\020Mount" +
      "PointsEntry\022\013\n\003key\030\001 \001(\t\0220\n\005value\030\002 \001(\0132" +
      "!.alluxio.grpc.file.MountPointInfo:\0028\001\"\027" +
      "\n\025GetMountTablePRequest\"\205\002\n\016MountPointIn" +
      "fo\022\016\n\006ufsUri\030\001 \001(\t\022\017\n\007ufsType\030\002 \001(\t\022\034\n\020u" +
      "fsCapacityBytes\030\003 \001(\003:\002-1\022\030\n\014ufsUsedByte" +
      "s\030\004 \001(\003:\002-1\022\020\n\010readOnly\030\005 \001(\010\022E\n\npropert" +
      "ies\030\006 \003(\01321.alluxio.grpc.file.MountPoint" +
      "Info.PropertiesEntry\022\016\n\006shared\030\007 \001(\010\0321\n\017" +
      "PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"\\\n\030FileSystemCommandOptions\022@\n\016p" +
      "ersistOptions\030\001 \001(\0132(.alluxio.grpc.file." +
      "PersistCommandOptions\"M\n\025PersistCommandO" +
      "ptions\0224\n\014persistFiles\030\001 \003(\0132\036.alluxio.g" +
      "rpc.file.PersistFile\"/\n\013PersistFile\022\016\n\006f" +
      "ileId\030\001 \001(\003\022\020\n\010blockIds\030\002 \003(\003\"\210\001\n\021FileSy" +
      "stemCommand\022.\n\013commandType\030\001 \001(\0162\031.allux" +
      "io.grpc.CommandType\022C\n\016commandOptions\030\002 " +
      "\001(\0132+.alluxio.grpc.file.FileSystemComman" +
      "dOptions\"\021\n\017RenamePResponse\"Z\n\016RenamePOp" +
      "tions\022H\n\rcommonOptions\030\001 \001(\01321.alluxio.g" +
      "rpc.file.FileSystemMasterCommonPOptions\"" +
      "c\n\016RenamePRequest\022\014\n\004path\030\001 \001(\t\022\017\n\007dstPa" +
      "th\030\002 \001(\t\0222\n\007options\030\003 \001(\0132!.alluxio.grpc" +
      ".file.RenamePOptions\"\027\n\025SetAttributePRes" +
      "ponse\"\300\002\n\024SetAttributePOptions\022\016\n\006pinned" +
      "\030\001 \001(\010\022\013\n\003ttl\030\002 \001(\003\022*\n\tttlAction\030\003 \001(\0162\027" +
      ".alluxio.grpc.TtlAction\022\021\n\tpersisted\030\004 \001" +
      "(\010\022\r\n\005owner\030\005 \001(\t\022\r\n\005group\030\006 \001(\t\022!\n\004mode" +
      "\030\007 \001(\0132\023.alluxio.grpc.PMode\022\021\n\trecursive" +
      "\030\010 \001(\010\022\026\n\016replicationMax\030\t \001(\005\022\026\n\016replic" +
      "ationMin\030\n \001(\005\022H\n\rcommonOptions\030\013 \001(\01321." +
      "alluxio.grpc.file.FileSystemMasterCommon" +
      "POptions\"^\n\024SetAttributePRequest\022\014\n\004path" +
      "\030\001 \001(\t\0228\n\007options\030\002 \001(\0132\'.alluxio.grpc.f" +
      "ile.SetAttributePOptions\"\021\n\017SetAclPRespo" +
      "nse\"m\n\016SetAclPOptions\022H\n\rcommonOptions\030\001" +
      " \001(\01321.alluxio.grpc.file.FileSystemMaste" +
      "rCommonPOptions\022\021\n\trecursive\030\002 \001(\010\"\262\001\n\016S" +
      "etAclPRequest\022\014\n\004path\030\001 \001(\t\022/\n\006action\030\002 " +
      "\001(\0162\037.alluxio.grpc.file.SetAclAction\022-\n\007" +
      "entries\030\003 \003(\0132\034.alluxio.grpc.file.PAclEn" +
      "try\0222\n\007options\030\004 \001(\0132!.alluxio.grpc.file" +
      ".SetAclPOptions\"#\n!ScheduleAsyncPersiste" +
      "ncePResponse\"l\n ScheduleAsyncPersistence" +
      "POptions\022H\n\rcommonOptions\030\001 \001(\01321.alluxi" +
      "o.grpc.file.FileSystemMasterCommonPOptio" +
      "ns\"v\n ScheduleAsyncPersistencePRequest\022\014" +
      "\n\004path\030\001 \001(\t\022D\n\007options\030\002 \001(\01323.alluxio." +
      "grpc.file.ScheduleAsyncPersistencePOptio" +
      "ns\"\024\n\022StartSyncPResponse\"]\n\021StartSyncPOp" +
      "tions\022H\n\rcommonOptions\030\001 \001(\01321.alluxio.g" +
      "rpc.file.FileSystemMasterCommonPOptions\"" +
      "X\n\021StartSyncPRequest\022\014\n\004path\030\001 \001(\t\0225\n\007op" +
      "tions\030\002 \001(\0132$.alluxio.grpc.file.StartSyn" +
      "cPOptions\"\023\n\021StopSyncPResponse\"\\\n\020StopSy" +
      "ncPOptions\022H\n\rcommonOptions\030\001 \001(\01321.allu" +
      "xio.grpc.file.FileSystemMasterCommonPOpt" +
      "ions\"V\n\020StopSyncPRequest\022\014\n\004path\030\001 \001(\t\0224" +
      "\n\007options\030\002 \001(\0132#.alluxio.grpc.file.Stop" +
      "SyncPOptions\"\022\n\020UnmountPResponse\"[\n\017Unmo" +
      "untPOptions\022H\n\rcommonOptions\030\001 \001(\01321.all" +
      "uxio.grpc.file.FileSystemMasterCommonPOp" +
      "tions\"[\n\017UnmountPRequest\022\023\n\013alluxioPath\030" +
      "\001 \001(\t\0223\n\007options\030\002 \001(\0132\".alluxio.grpc.fi" +
      "le.UnmountPOptions\"L\n\007UfsInfo\022\013\n\003uri\030\001 \001" +
      "(\t\0224\n\nproperties\030\002 \001(\0132 .alluxio.grpc.fi" +
      "le.MountPOptions\"\030\n\026UpdateUfsModePRespon" +
      "se\"E\n\025UpdateUfsModePOptions\022,\n\007ufsMode\030\001" +
      " \001(\0162\033.alluxio.grpc.file.UfsPMode\"c\n\025Upd" +
      "ateUfsModePRequest\022\017\n\007ufsPath\030\001 \001(\t\0229\n\007o" +
      "ptions\030\002 \001(\0132(.alluxio.grpc.file.UpdateU" +
      "fsModePOptions\"U\n\034FileSystemHeartbeatPRe" +
      "sponse\0225\n\007command\030\001 \001(\0132$.alluxio.grpc.f" +
      "ile.FileSystemCommand\"@\n\033FileSystemHeart" +
      "beatPOptions\022!\n\031persistedFileFingerprint" +
      "s\030\001 \003(\t\"\210\001\n\033FileSystemHeartbeatPRequest\022" +
      "\020\n\010workerId\030\001 \001(\003\022\026\n\016persistedFiles\030\002 \003(" +
      "\003\022?\n\007options\030\003 \001(\0132..alluxio.grpc.file.F" +
      "ileSystemHeartbeatPOptions\"E\n\024GetFileInf" +
      "oPResponse\022-\n\010fileInfo\030\001 \001(\0132\033.alluxio.g" +
      "rpc.file.FileInfo\"\025\n\023GetFileInfoPOptions" +
      "\"^\n\023GetFileInfoPRequest\022\016\n\006fileId\030\001 \001(\003\022" +
      "7\n\007options\030\002 \001(\0132&.alluxio.grpc.file.Get" +
      "FileInfoPOptions\"2\n\031GetPinnedFileIdsPRes" +
      "ponse\022\025\n\rpinnedFileIds\030\001 \003(\003\"\032\n\030GetPinne" +
      "dFileIdsPOptions\"X\n\030GetPinnedFileIdsPReq" +
      "uest\022<\n\007options\030\001 \001(\0132+.alluxio.grpc.fil" +
      "e.GetPinnedFileIdsPOptions\"B\n\023GetUfsInfo" +
      "PResponse\022+\n\007ufsInfo\030\001 \001(\0132\032.alluxio.grp" +
      "c.file.UfsInfo\"\024\n\022GetUfsInfoPOptions\"]\n\022" +
      "GetUfsInfoPRequest\022\017\n\007mountId\030\001 \001(\003\0226\n\007o" +
      "ptions\030\002 \001(\0132%.alluxio.grpc.file.GetUfsI" +
      "nfoPOptions*h\n\nWritePType\022\016\n\nMUST_CACHE\020" +
      "\001\022\r\n\tTRY_CACHE\020\002\022\021\n\rCACHE_THROUGH\020\003\022\013\n\007T" +
      "HROUGH\020\004\022\021\n\rASYNC_THROUGH\020\005\022\010\n\004NONE\020\006*7\n" +
      "\tReadPType\022\014\n\010NO_CACHE\020\001\022\t\n\005CACHE\020\002\022\021\n\rC" +
      "ACHE_PROMOTE\020\003*4\n\021LoadMetadataPType\022\t\n\005N" +
      "EVER\020\000\022\010\n\004ONCE\020\001\022\n\n\006ALWAYS\020\002*N\n\017SyncPoin" +
      "tStatus\022\030\n\024Not_Initially_Synced\020\000\022\013\n\007Syn" +
      "cing\020\001\022\024\n\020Initially_Synced\020\002*_\n\rPAclEntr" +
      "yType\022\t\n\005Owner\020\000\022\r\n\tNamedUser\020\001\022\017\n\013Ownin" +
      "gGroup\020\002\022\016\n\nNamedGroup\020\003\022\010\n\004Mask\020\004\022\t\n\005Ot" +
      "her\020\005*.\n\nPAclAction\022\010\n\004Read\020\000\022\t\n\005Write\020\001" +
      "\022\013\n\007Execute\020\002*W\n\014SetAclAction\022\013\n\007REPLACE" +
      "\020\000\022\n\n\006MODIFY\020\001\022\n\n\006REMOVE\020\002\022\016\n\nREMOVE_ALL" +
      "\020\003\022\022\n\016REMOVE_DEFAULT\020\004*8\n\010UfsPMode\022\r\n\tNO" +
      "_ACCESS\020\001\022\r\n\tREAD_ONLY\020\002\022\016\n\nREAD_WRITE\020\003" +
      "2\240\017\n\035FileSystemMasterClientService\022m\n\020Ch" +
      "eckConsistency\022+.alluxio.grpc.file.Check" +
      "ConsistencyPRequest\032,.alluxio.grpc.file." +
      "CheckConsistencyPResponse\022a\n\014CompleteFil" +
      "e\022\'.alluxio.grpc.file.CompleteFilePReque" +
      "st\032(.alluxio.grpc.file.CompleteFilePResp" +
      "onse\022j\n\017CreateDirectory\022*.alluxio.grpc.f" +
      "ile.CreateDirectoryPRequest\032+.alluxio.gr" +
      "pc.file.CreateDirectoryPResponse\022[\n\nCrea" +
      "teFile\022%.alluxio.grpc.file.CreateFilePRe" +
      "quest\032&.alluxio.grpc.file.CreateFilePRes" +
      "ponse\022I\n\004Free\022\037.alluxio.grpc.file.FreePR" +
      "equest\032 .alluxio.grpc.file.FreePResponse" +
      "\022d\n\rGetMountTable\022(.alluxio.grpc.file.Ge" +
      "tMountTablePRequest\032).alluxio.grpc.file." +
      "GetMountTablePResponse\022j\n\017GetSyncPathLis" +
      "t\022*.alluxio.grpc.file.GetSyncPathListPRe" +
      "quest\032+.alluxio.grpc.file.GetSyncPathLis" +
      "tPResponse\022y\n\024GetNewBlockIdForFile\022/.all" +
      "uxio.grpc.file.GetNewBlockIdForFilePRequ" +
      "est\0320.alluxio.grpc.file.GetNewBlockIdFor" +
      "FilePResponse\022X\n\tGetStatus\022$.alluxio.grp" +
      "c.file.GetStatusPRequest\032%.alluxio.grpc." +
      "file.GetStatusPResponse\022[\n\nListStatus\022%." +
      "alluxio.grpc.file.ListStatusPRequest\032&.a" +
      "lluxio.grpc.file.ListStatusPResponse\022L\n\005" +
      "Mount\022 .alluxio.grpc.file.MountPRequest\032" +
      "!.alluxio.grpc.file.MountPResponse\022O\n\006Re" +
      "move\022!.alluxio.grpc.file.DeletePRequest\032" +
      "\".alluxio.grpc.file.DeletePResponse\022O\n\006R" +
      "ename\022!.alluxio.grpc.file.RenamePRequest" +
      "\032\".alluxio.grpc.file.RenamePResponse\022\205\001\n" +
      "\030ScheduleAsyncPersistence\0223.alluxio.grpc" +
      ".file.ScheduleAsyncPersistencePRequest\0324" +
      ".alluxio.grpc.file.ScheduleAsyncPersiste" +
      "ncePResponse\022O\n\006SetAcl\022!.alluxio.grpc.fi" +
      "le.SetAclPRequest\032\".alluxio.grpc.file.Se" +
      "tAclPResponse\022a\n\014SetAttribute\022\'.alluxio." +
      "grpc.file.SetAttributePRequest\032(.alluxio" +
      ".grpc.file.SetAttributePResponse\022X\n\tStar" +
      "tSync\022$.alluxio.grpc.file.StartSyncPRequ" +
      "est\032%.alluxio.grpc.file.StartSyncPRespon" +
      "se\022U\n\010StopSync\022#.alluxio.grpc.file.StopS" +
      "yncPRequest\032$.alluxio.grpc.file.StopSync" +
      "PResponse\022R\n\007Unmount\022\".alluxio.grpc.file" +
      ".UnmountPRequest\032#.alluxio.grpc.file.Unm" +
      "ountPResponse\022d\n\rUpdateUfsMode\022(.alluxio" +
      ".grpc.file.UpdateUfsModePRequest\032).allux" +
      "io.grpc.file.UpdateUfsModePResponse2\303\003\n\035" +
      "FileSystemMasterWorkerService\022v\n\023FileSys" +
      "temHeartbeat\022..alluxio.grpc.file.FileSys" +
      "temHeartbeatPRequest\032/.alluxio.grpc.file" +
      ".FileSystemHeartbeatPResponse\022^\n\013GetFile" +
      "Info\022&.alluxio.grpc.file.GetFileInfoPReq" +
      "uest\032\'.alluxio.grpc.file.GetFileInfoPRes" +
      "ponse\022m\n\020GetPinnedFileIds\022+.alluxio.grpc" +
      ".file.GetPinnedFileIdsPRequest\032,.alluxio" +
      ".grpc.file.GetPinnedFileIdsPResponse\022[\n\n" +
      "GetUfsInfo\022%.alluxio.grpc.file.GetUfsInf" +
      "oPRequest\032&.alluxio.grpc.file.GetUfsInfo" +
      "PResponse2\331\001\n\032FileSystemMasterJobService" +
      "\022^\n\013GetFileInfo\022&.alluxio.grpc.file.GetF" +
      "ileInfoPRequest\032\'.alluxio.grpc.file.GetF" +
      "ileInfoPResponse\022[\n\nGetUfsInfo\022%.alluxio" +
      ".grpc.file.GetUfsInfoPRequest\032&.alluxio." +
      "grpc.file.GetUfsInfoPResponseB\'\n\014alluxio" +
      ".grpcB\025FileSystemMasterProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          alluxio.grpc.CommonProto.getDescriptor(),
          alluxio.grpc.FsCommonProto.getDescriptor(),
        }, assigner);
    internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_descriptor,
        new java.lang.String[] { "SyncIntervalMs", "Ttl", "TtlAction", });
    internal_static_alluxio_grpc_file_CheckConsistencyPResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alluxio_grpc_file_CheckConsistencyPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CheckConsistencyPResponse_descriptor,
        new java.lang.String[] { "InconsistentPaths", });
    internal_static_alluxio_grpc_file_CheckConsistencyPOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alluxio_grpc_file_CheckConsistencyPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CheckConsistencyPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_CheckConsistencyPRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_alluxio_grpc_file_CheckConsistencyPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CheckConsistencyPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_CompleteFilePResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_alluxio_grpc_file_CompleteFilePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CompleteFilePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CompleteFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_alluxio_grpc_file_CompleteFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CompleteFilePOptions_descriptor,
        new java.lang.String[] { "UfsLength", "CommonOptions", });
    internal_static_alluxio_grpc_file_CompleteFilePRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_alluxio_grpc_file_CompleteFilePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CompleteFilePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_OpenFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_alluxio_grpc_file_OpenFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_OpenFilePOptions_descriptor,
        new java.lang.String[] { "ReadType", "MaxUfsReadConcurrency", "FileReadLocationPolicy", "HashingNumberOfShards", "CommonOptions", });
    internal_static_alluxio_grpc_file_CreateDirectoryPResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_alluxio_grpc_file_CreateDirectoryPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateDirectoryPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CreateDirectoryPOptions_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_alluxio_grpc_file_CreateDirectoryPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateDirectoryPOptions_descriptor,
        new java.lang.String[] { "Recursive", "AllowExists", "Mode", "WriteType", "CommonOptions", });
    internal_static_alluxio_grpc_file_CreateDirectoryPRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_alluxio_grpc_file_CreateDirectoryPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateDirectoryPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_CreateFilePResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_alluxio_grpc_file_CreateFilePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateFilePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CreateFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_alluxio_grpc_file_CreateFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateFilePOptions_descriptor,
        new java.lang.String[] { "BlockSizeBytes", "Recursive", "Mode", "ReplicationMax", "ReplicationMin", "ReplicationDurable", "FileWriteLocationPolicy", "WriteTier", "WriteType", "CommonOptions", });
    internal_static_alluxio_grpc_file_CreateFilePRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_alluxio_grpc_file_CreateFilePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateFilePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_DeletePResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_alluxio_grpc_file_DeletePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DeletePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_DeletePOptions_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_alluxio_grpc_file_DeletePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DeletePOptions_descriptor,
        new java.lang.String[] { "Recursive", "AlluxioOnly", "Unchecked", "CommonOptions", });
    internal_static_alluxio_grpc_file_DeletePRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_alluxio_grpc_file_DeletePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DeletePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_FreePResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_alluxio_grpc_file_FreePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FreePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_FreePOptions_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_alluxio_grpc_file_FreePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FreePOptions_descriptor,
        new java.lang.String[] { "Recursive", "Forced", "CommonOptions", });
    internal_static_alluxio_grpc_file_FreePRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_alluxio_grpc_file_FreePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FreePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_GetStatusPResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_alluxio_grpc_file_GetStatusPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetStatusPResponse_descriptor,
        new java.lang.String[] { "FileInfo", });
    internal_static_alluxio_grpc_file_GetStatusPOptions_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_alluxio_grpc_file_GetStatusPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetStatusPOptions_descriptor,
        new java.lang.String[] { "LoadMetadataType", "CommonOptions", });
    internal_static_alluxio_grpc_file_GetStatusPRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_alluxio_grpc_file_GetStatusPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetStatusPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_ExistsPOptions_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_alluxio_grpc_file_ExistsPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ExistsPOptions_descriptor,
        new java.lang.String[] { "LoadMetadataType", "CommonOptions", });
    internal_static_alluxio_grpc_file_SyncPointInfo_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_alluxio_grpc_file_SyncPointInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SyncPointInfo_descriptor,
        new java.lang.String[] { "SyncPointUri", "SyncStatus", });
    internal_static_alluxio_grpc_file_GetSyncPathListPResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_alluxio_grpc_file_GetSyncPathListPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetSyncPathListPResponse_descriptor,
        new java.lang.String[] { "SyncPaths", });
    internal_static_alluxio_grpc_file_GetSyncPathListPRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_alluxio_grpc_file_GetSyncPathListPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetSyncPathListPRequest_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_ListStatusPResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_alluxio_grpc_file_ListStatusPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ListStatusPResponse_descriptor,
        new java.lang.String[] { "FileInfos", });
    internal_static_alluxio_grpc_file_ListStatusPOptions_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_alluxio_grpc_file_ListStatusPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ListStatusPOptions_descriptor,
        new java.lang.String[] { "LoadDirectChildren", "LoadMetadataType", "CommonOptions", "Recursive", });
    internal_static_alluxio_grpc_file_ListStatusPRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_alluxio_grpc_file_ListStatusPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ListStatusPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_LoadMetadataPResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_alluxio_grpc_file_LoadMetadataPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_LoadMetadataPResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_alluxio_grpc_file_LoadMetadataPOptions_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_alluxio_grpc_file_LoadMetadataPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_LoadMetadataPOptions_descriptor,
        new java.lang.String[] { "Recursive", "CreateAncestors", "LoadDescendantType", "CommonOptions", });
    internal_static_alluxio_grpc_file_LoadMetadataPRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_alluxio_grpc_file_LoadMetadataPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_LoadMetadataPRequest_descriptor,
        new java.lang.String[] { "UfsPath", "Options", });
    internal_static_alluxio_grpc_file_PAclEntry_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_alluxio_grpc_file_PAclEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PAclEntry_descriptor,
        new java.lang.String[] { "Type", "Subject", "Actions", "IsDefault", });
    internal_static_alluxio_grpc_file_PAcl_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_alluxio_grpc_file_PAcl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PAcl_descriptor,
        new java.lang.String[] { "Owner", "OwningGroup", "Entries", "Mode", "IsDefault", "IsDefaultEmpty", });
    internal_static_alluxio_grpc_file_FileBlockInfo_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_alluxio_grpc_file_FileBlockInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileBlockInfo_descriptor,
        new java.lang.String[] { "BlockInfo", "Offset", "UfsLocations", "UfsStringLocations", });
    internal_static_alluxio_grpc_file_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_alluxio_grpc_file_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileInfo_descriptor,
        new java.lang.String[] { "FileId", "Name", "Path", "UfsPath", "Length", "BlockSizeBytes", "CreationTimeMs", "Completed", "Folder", "Pinned", "Cacheable", "Persisted", "BlockIds", "LastModificationTimeMs", "Ttl", "Owner", "Group", "Mode", "PersistenceState", "MountPoint", "FileBlockInfos", "TtlAction", "MountId", "InAlluxioPercentage", "InMemoryPercentage", "UfsFingerprint", "Acl", "DefaultAcl", "ReplicationMax", "ReplicationMin", });
    internal_static_alluxio_grpc_file_MountPResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_alluxio_grpc_file_MountPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_MountPOptions_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_alluxio_grpc_file_MountPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPOptions_descriptor,
        new java.lang.String[] { "ReadOnly", "Properties", "Shared", "CommonOptions", });
    internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_descriptor =
      internal_static_alluxio_grpc_file_MountPOptions_descriptor.getNestedTypes().get(0);
    internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_alluxio_grpc_file_MountPRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_alluxio_grpc_file_MountPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPRequest_descriptor,
        new java.lang.String[] { "AlluxioPath", "UfsPath", "Options", });
    internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_alluxio_grpc_file_GetMountTablePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor,
        new java.lang.String[] { "MountPoints", });
    internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_descriptor =
      internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor.getNestedTypes().get(0);
    internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_alluxio_grpc_file_GetMountTablePRequest_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_alluxio_grpc_file_GetMountTablePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetMountTablePRequest_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_MountPointInfo_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_alluxio_grpc_file_MountPointInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPointInfo_descriptor,
        new java.lang.String[] { "UfsUri", "UfsType", "UfsCapacityBytes", "UfsUsedBytes", "ReadOnly", "Properties", "Shared", });
    internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_descriptor =
      internal_static_alluxio_grpc_file_MountPointInfo_descriptor.getNestedTypes().get(0);
    internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_alluxio_grpc_file_FileSystemCommandOptions_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_alluxio_grpc_file_FileSystemCommandOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemCommandOptions_descriptor,
        new java.lang.String[] { "PersistOptions", });
    internal_static_alluxio_grpc_file_PersistCommandOptions_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_alluxio_grpc_file_PersistCommandOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PersistCommandOptions_descriptor,
        new java.lang.String[] { "PersistFiles", });
    internal_static_alluxio_grpc_file_PersistFile_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_alluxio_grpc_file_PersistFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PersistFile_descriptor,
        new java.lang.String[] { "FileId", "BlockIds", });
    internal_static_alluxio_grpc_file_FileSystemCommand_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_alluxio_grpc_file_FileSystemCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemCommand_descriptor,
        new java.lang.String[] { "CommandType", "CommandOptions", });
    internal_static_alluxio_grpc_file_RenamePResponse_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_alluxio_grpc_file_RenamePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenamePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_RenamePOptions_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_alluxio_grpc_file_RenamePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenamePOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_RenamePRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_alluxio_grpc_file_RenamePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenamePRequest_descriptor,
        new java.lang.String[] { "Path", "DstPath", "Options", });
    internal_static_alluxio_grpc_file_SetAttributePResponse_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_alluxio_grpc_file_SetAttributePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAttributePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_SetAttributePOptions_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_alluxio_grpc_file_SetAttributePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAttributePOptions_descriptor,
        new java.lang.String[] { "Pinned", "Ttl", "TtlAction", "Persisted", "Owner", "Group", "Mode", "Recursive", "ReplicationMax", "ReplicationMin", "CommonOptions", });
    internal_static_alluxio_grpc_file_SetAttributePRequest_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_alluxio_grpc_file_SetAttributePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAttributePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_SetAclPResponse_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_alluxio_grpc_file_SetAclPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAclPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_SetAclPOptions_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_alluxio_grpc_file_SetAclPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAclPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", "Recursive", });
    internal_static_alluxio_grpc_file_SetAclPRequest_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_alluxio_grpc_file_SetAclPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAclPRequest_descriptor,
        new java.lang.String[] { "Path", "Action", "Entries", "Options", });
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_StartSyncPResponse_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_alluxio_grpc_file_StartSyncPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StartSyncPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_StartSyncPOptions_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_alluxio_grpc_file_StartSyncPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StartSyncPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_StartSyncPRequest_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_alluxio_grpc_file_StartSyncPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StartSyncPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_StopSyncPResponse_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_alluxio_grpc_file_StopSyncPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StopSyncPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_StopSyncPOptions_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_alluxio_grpc_file_StopSyncPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StopSyncPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_StopSyncPRequest_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_alluxio_grpc_file_StopSyncPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StopSyncPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_UnmountPResponse_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_alluxio_grpc_file_UnmountPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UnmountPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_UnmountPOptions_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_alluxio_grpc_file_UnmountPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UnmountPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_UnmountPRequest_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_alluxio_grpc_file_UnmountPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UnmountPRequest_descriptor,
        new java.lang.String[] { "AlluxioPath", "Options", });
    internal_static_alluxio_grpc_file_UfsInfo_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_alluxio_grpc_file_UfsInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UfsInfo_descriptor,
        new java.lang.String[] { "Uri", "Properties", });
    internal_static_alluxio_grpc_file_UpdateUfsModePResponse_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_alluxio_grpc_file_UpdateUfsModePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UpdateUfsModePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_UpdateUfsModePOptions_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_alluxio_grpc_file_UpdateUfsModePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UpdateUfsModePOptions_descriptor,
        new java.lang.String[] { "UfsMode", });
    internal_static_alluxio_grpc_file_UpdateUfsModePRequest_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_alluxio_grpc_file_UpdateUfsModePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UpdateUfsModePRequest_descriptor,
        new java.lang.String[] { "UfsPath", "Options", });
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_descriptor,
        new java.lang.String[] { "PersistedFileFingerprints", });
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_descriptor,
        new java.lang.String[] { "WorkerId", "PersistedFiles", "Options", });
    internal_static_alluxio_grpc_file_GetFileInfoPResponse_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_alluxio_grpc_file_GetFileInfoPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetFileInfoPResponse_descriptor,
        new java.lang.String[] { "FileInfo", });
    internal_static_alluxio_grpc_file_GetFileInfoPOptions_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_alluxio_grpc_file_GetFileInfoPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetFileInfoPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_GetFileInfoPRequest_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_alluxio_grpc_file_GetFileInfoPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetFileInfoPRequest_descriptor,
        new java.lang.String[] { "FileId", "Options", });
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_descriptor,
        new java.lang.String[] { "PinnedFileIds", });
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_alluxio_grpc_file_GetUfsInfoPResponse_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_alluxio_grpc_file_GetUfsInfoPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetUfsInfoPResponse_descriptor,
        new java.lang.String[] { "UfsInfo", });
    internal_static_alluxio_grpc_file_GetUfsInfoPOptions_descriptor =
      getDescriptor().getMessageTypes().get(85);
    internal_static_alluxio_grpc_file_GetUfsInfoPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetUfsInfoPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_GetUfsInfoPRequest_descriptor =
      getDescriptor().getMessageTypes().get(86);
    internal_static_alluxio_grpc_file_GetUfsInfoPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetUfsInfoPRequest_descriptor,
        new java.lang.String[] { "MountId", "Options", });
    alluxio.grpc.CommonProto.getDescriptor();
    alluxio.grpc.FsCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
