// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/meta_master.proto

package alluxio.grpc;

public interface GetMetricsPOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.meta.GetMetricsPOptions)
    com.google.protobuf.MessageOrBuilder {
}
