// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_master.proto

package alluxio.grpc;

public interface GetWorkerAddressesPResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.block.GetWorkerAddressesPResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .alluxio.grpc.WorkerNetAddress workerAddresses = 1;</code>
   */
  java.util.List<alluxio.grpc.WorkerNetAddress> 
      getWorkerAddressesList();
  /**
   * <code>repeated .alluxio.grpc.WorkerNetAddress workerAddresses = 1;</code>
   */
  alluxio.grpc.WorkerNetAddress getWorkerAddresses(int index);
  /**
   * <code>repeated .alluxio.grpc.WorkerNetAddress workerAddresses = 1;</code>
   */
  int getWorkerAddressesCount();
  /**
   * <code>repeated .alluxio.grpc.WorkerNetAddress workerAddresses = 1;</code>
   */
  java.util.List<? extends alluxio.grpc.WorkerNetAddressOrBuilder> 
      getWorkerAddressesOrBuilderList();
  /**
   * <code>repeated .alluxio.grpc.WorkerNetAddress workerAddresses = 1;</code>
   */
  alluxio.grpc.WorkerNetAddressOrBuilder getWorkerAddressesOrBuilder(
      int index);
}
