// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta_master.proto

package alluxio.grpc;

public interface InconsistentPropertiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.InconsistentProperties)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .alluxio.grpc.InconsistentProperty properties = 1;</code>
   */
  java.util.List<alluxio.grpc.InconsistentProperty> 
      getPropertiesList();
  /**
   * <code>repeated .alluxio.grpc.InconsistentProperty properties = 1;</code>
   */
  alluxio.grpc.InconsistentProperty getProperties(int index);
  /**
   * <code>repeated .alluxio.grpc.InconsistentProperty properties = 1;</code>
   */
  int getPropertiesCount();
  /**
   * <code>repeated .alluxio.grpc.InconsistentProperty properties = 1;</code>
   */
  java.util.List<? extends alluxio.grpc.InconsistentPropertyOrBuilder> 
      getPropertiesOrBuilderList();
  /**
   * <code>repeated .alluxio.grpc.InconsistentProperty properties = 1;</code>
   */
  alluxio.grpc.InconsistentPropertyOrBuilder getPropertiesOrBuilder(
      int index);
}
