// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_worker.proto

package alluxio.grpc;

public interface MoveBlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.block.MoveBlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 block_id = 1;</code>
   */
  boolean hasBlockId();
  /**
   * <code>optional int64 block_id = 1;</code>
   */
  long getBlockId();

  /**
   * <code>optional .alluxio.grpc.BlockStoreLocationProto src = 2;</code>
   */
  boolean hasSrc();
  /**
   * <code>optional .alluxio.grpc.BlockStoreLocationProto src = 2;</code>
   */
  alluxio.grpc.BlockStoreLocationProto getSrc();
  /**
   * <code>optional .alluxio.grpc.BlockStoreLocationProto src = 2;</code>
   */
  alluxio.grpc.BlockStoreLocationProtoOrBuilder getSrcOrBuilder();

  /**
   * <code>optional .alluxio.grpc.BlockStoreLocationProto dst = 3;</code>
   */
  boolean hasDst();
  /**
   * <code>optional .alluxio.grpc.BlockStoreLocationProto dst = 3;</code>
   */
  alluxio.grpc.BlockStoreLocationProto getDst();
  /**
   * <code>optional .alluxio.grpc.BlockStoreLocationProto dst = 3;</code>
   */
  alluxio.grpc.BlockStoreLocationProtoOrBuilder getDstOrBuilder();
}
