// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/catalog_master.proto

package alluxio.grpc;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 integer_type = 1;</code>
   */
  boolean hasIntegerType();
  /**
   * <code>optional int64 integer_type = 1;</code>
   */
  long getIntegerType();

  /**
   * <code>optional float double_type = 2;</code>
   */
  boolean hasDoubleType();
  /**
   * <code>optional float double_type = 2;</code>
   */
  float getDoubleType();

  /**
   * <code>optional string string_type = 3;</code>
   */
  boolean hasStringType();
  /**
   * <code>optional string string_type = 3;</code>
   */
  java.lang.String getStringType();
  /**
   * <code>optional string string_type = 3;</code>
   */
  com.google.protobuf.ByteString
      getStringTypeBytes();

  /**
   * <code>optional bool boolean_type = 4;</code>
   */
  boolean hasBooleanType();
  /**
   * <code>optional bool boolean_type = 4;</code>
   */
  boolean getBooleanType();

  public alluxio.grpc.Value.ValueCase getValueCase();
}
