/*
 * The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
 * (the "License"). You may not use this work except in compliance with the License, which is
 * available at www.apache.org/licenses/LICENSE-2.0
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied, as more fully set forth in the License.
 *
 * See the NOTICE file distributed with this work for information regarding copyright ownership.
 */
{"version":["sessionrestore",1],"windows":[{"tabs":[{"entries":[{"url":"about:home","title":"Mozilla Firefox Start Page","charset":"","ID":2,"docshellID":5,"docIdentifier":2,"persist":true},{"url":"https://www.baidu.com/","title":"百度一下，你就知道","charset":"UTF-8","ID":4,"docshellID":5,"originalURI":"http://www.baidu.com/","loadReplace":true,"docIdentifier":4,"persist":true}],"lastAccessed":1522073902537,"hidden":false,"attributes":{},"index":2,"image":"https://www.baidu.com/img/baidu_85beaf5496f291521eb75ba38eacbd87.svg"},{"entries":[{"url":"http://cs.nju.edu.cn/","title":"计算机系主页","charset":"UTF-8","ID":7,"docshellID":8,"originalURI":"http://cs.nju.edu.cn/","docIdentifier":7,"persist":true},{"url":"http://cs.nju.edu.cn/1651/list.htm","title":"师资队伍","charset":"UTF-8","ID":8,"docshellID":8,"referrer":"http://cs.nju.edu.cn/","referrerPolicy":0,"originalURI":"http://cs.nju.edu.cn/1651/list.htm","docIdentifier":8,"persist":true}],"lastAccessed":1522073938872,"hidden":false,"attributes":{},"index":2,"scroll":{"scroll":"0,285"},"image":null},{"entries":[{"url":"http://cs.nju.edu.cn/58/00/c2639a153600/page.htm","title":"许畅 (博导)","charset":"UTF-8","ID":9,"docshellID":11,"referrer":"http://cs.nju.edu.cn/1651/list.htm","referrerPolicy":0,"originalURI":"http://cs.nju.edu.cn/58/00/c2639a153600/page.htm","docIdentifier":9,"persist":true}],"lastAccessed":1522073942902,"hidden":false,"attributes":{},"index":1,"scroll":{"scroll":"453,215"},"image":null},{"entries":[{"url":"http://cs.nju.edu.cn/changxu/","title":"Welcome to Chang Xu's homepage","charset":"UTF-8","ID":10,"docshellID":12,"referrer":"http://cs.nju.edu.cn/58/00/c2639a153600/page.htm","referrerPolicy":0,"originalURI":"http://cs.nju.edu.cn/changxu","loadReplace":true,"docIdentifier":10,"persist":true},{"url":"http://cs.nju.edu.cn/changxu/2_compiler/index.html","title":"编译原理（2018年春季）","charset":"UTF-8","ID":11,"docshellID":12,"referrer":"http://cs.nju.edu.cn/changxu/","referrerPolicy":0,"originalURI":"http://cs.nju.edu.cn/changxu/2_compiler/index.html","docIdentifier":11,"persist":true}],"lastAccessed":1522074185276,"hidden":false,"attributes":{},"index":2,"scroll":{"scroll":"0,1596"},"image":null}],"selected":4,"_closedTabs":[],"width":"610","height":"422","screenX":"65","screenY":"24","sizemode":"maximized","cookies":[{"host":"www.baidu.com","value":"0","path":"/","name":"BD_HOME"},{"host":".baidu.com","value":"1431_21081_18560","path":"/","name":"H_PS_PSSID"},{"host":"cs.nju.edu.cn","value":"98184645","path":"/","name":"www.nju.edu.cn"}],"title":"编译原理（2018年春季）","_shouldRestore":true,"closedAt":1522074185303}],"selectedWindow":0,"_closedWindows":[],"session":{"lastUpdate":1522074185507,"startTime":1522073874499,"recentCrashes":0},"global":{}}