#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# See https://hub.docker.com/r/alluxio/alluxio-maven for instructions on running the image.

FROM maven:3.6.3-jdk-8

# need to create /.config to avoid npm errors
RUN mkdir -p /home/jenkins && \
    chmod -R 777 /home/jenkins && \
    chmod g+w /etc/passwd && \
    mkdir -p /.config && \
    chmod -R 777 /.config && \
    apt-get update -y && \
    apt-get upgrade -y ca-certificates && \
    apt-get install -y build-essential fuse libfuse-dev make ruby ruby-dev
# jekyll for documentation
RUN gem install jekyll bundler
# golang for tooling
RUN ARCH=$(dpkg --print-architecture) && \
    wget https://go.dev/dl/go1.18.1.linux-${ARCH}.tar.gz && \
    tar -xvf go1.18.1.linux-${ARCH}.tar.gz && \
    mv go /usr/local
ENV GOROOT=/usr/local/go
ENV PATH=$GOROOT/bin:$PATH
# terraform for deployment scripts
RUN ARCH=$(dpkg --print-architecture) && \
    wget --quiet https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_${ARCH}.zip && \
    unzip -o ./terraform_1.0.1_linux_${ARCH}.zip -d /usr/local/bin/ && \
    rm terraform_1.0.1_linux_${ARCH}.zip
