#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# See https://hub.docker.com/r/alluxio/alluxio-maven for instructions on running the image.

FROM maven:3.6.3-jdk-8

# need to create /.config to avoid npm errors
RUN mkdir -p /home/jenkins && \
    chmod -R 777 /home/jenkins && \
    chmod g+w /etc/passwd && \
    mkdir -p /.config && \
    chmod -R 777 /.config && \
    apt-get update -y && \
    apt-get upgrade -y ca-certificates && \
    apt-get install -y build-essential fuse make ruby ruby-dev
# jekyll for documentation
RUN gem install jekyll bundler
# golang for tooling
RUN wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz && \
    tar -xvf go1.12.linux-amd64.tar.gz && \
    mv go /usr/local
ENV GOROOT=/usr/local/go
ENV PATH=$GOROOT/bin:$PATH
# terraform for deployment scripts
RUN wget --quiet https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip && \
    unzip -o ./terraform_0.12.24_linux_amd64.zip -d /usr/local/bin/ && \
    rm terraform_0.12.24_linux_amd64.zip
