#!/usr/bin/env bash
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# Check we are in the root directory.
if test ! -f configure.ac; then
    cat >&2 <<__EOF__
You must run bootstrap from the root of the distribution.
__EOF__
    exit 1
fi

autoreconf --install -Wall --verbose "${@}"
