/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alluxio_jnifuse_FuseFiller */

#ifndef _Included_alluxio_jnifuse_FuseFiller
#define _Included_alluxio_jnifuse_FuseFiller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alluxio_jnifuse_FuseFiller
 * Method:    doFill
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_alluxio_jnifuse_FuseFiller_doFill
  (JNIEnv *, jobject, jlong, jstring, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
