// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/job_master.proto

package alluxio.grpc;

/**
 * Protobuf type {@code alluxio.grpc.job.CmdSummary}
 */
public final class CmdSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alluxio.grpc.job.CmdSummary)
    CmdSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CmdSummary.newBuilder() to construct.
  private CmdSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CmdSummary() {
    operationType_ = 1;
    jobSource_ = 0;
    status_ = 0;
    errorMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CmdSummary();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CmdSummary(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            jobControlId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            alluxio.grpc.OperationType value = alluxio.grpc.OperationType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              operationType_ = rawValue;
            }
            break;
          }
          case 24: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            alluxio.grpc.JobSource value = alluxio.grpc.JobSource.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(3, rawValue);
            } else {
              bitField0_ |= 0x00000004;
              jobSource_ = rawValue;
            }
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            alluxio.grpc.Status value = alluxio.grpc.Status.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(4, rawValue);
            } else {
              bitField0_ |= 0x00000008;
              status_ = rawValue;
            }
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            submissionTime_ = input.readInt64();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            duration_ = input.readInt64();
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            errorMessage_ = bs;
            break;
          }
          case 66: {
            alluxio.grpc.CmdProgress.Builder subBuilder = null;
            if (((bitField0_ & 0x00000080) != 0)) {
              subBuilder = cmdProgress_.toBuilder();
            }
            cmdProgress_ = input.readMessage(alluxio.grpc.CmdProgress.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cmdProgress_);
              cmdProgress_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000080;
            break;
          }
          case 77: {
            bitField0_ |= 0x00000100;
            progressPercentage_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return alluxio.grpc.JobMasterProto.internal_static_alluxio_grpc_job_CmdSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return alluxio.grpc.JobMasterProto.internal_static_alluxio_grpc_job_CmdSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            alluxio.grpc.CmdSummary.class, alluxio.grpc.CmdSummary.Builder.class);
  }

  private int bitField0_;
  public static final int JOBCONTROLID_FIELD_NUMBER = 1;
  private long jobControlId_;
  /**
   * <code>optional int64 jobControlId = 1;</code>
   * @return Whether the jobControlId field is set.
   */
  @java.lang.Override
  public boolean hasJobControlId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 jobControlId = 1;</code>
   * @return The jobControlId.
   */
  @java.lang.Override
  public long getJobControlId() {
    return jobControlId_;
  }

  public static final int OPERATIONTYPE_FIELD_NUMBER = 2;
  private int operationType_;
  /**
   * <code>optional .alluxio.grpc.job.OperationType operationType = 2;</code>
   * @return Whether the operationType field is set.
   */
  @java.lang.Override public boolean hasOperationType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .alluxio.grpc.job.OperationType operationType = 2;</code>
   * @return The operationType.
   */
  @java.lang.Override public alluxio.grpc.OperationType getOperationType() {
    @SuppressWarnings("deprecation")
    alluxio.grpc.OperationType result = alluxio.grpc.OperationType.valueOf(operationType_);
    return result == null ? alluxio.grpc.OperationType.DIST_LOAD : result;
  }

  public static final int JOBSOURCE_FIELD_NUMBER = 3;
  private int jobSource_;
  /**
   * <code>optional .alluxio.grpc.job.JobSource jobSource = 3;</code>
   * @return Whether the jobSource field is set.
   */
  @java.lang.Override public boolean hasJobSource() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .alluxio.grpc.job.JobSource jobSource = 3;</code>
   * @return The jobSource.
   */
  @java.lang.Override public alluxio.grpc.JobSource getJobSource() {
    @SuppressWarnings("deprecation")
    alluxio.grpc.JobSource result = alluxio.grpc.JobSource.valueOf(jobSource_);
    return result == null ? alluxio.grpc.JobSource.UNSUPPORTED : result;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <code>optional .alluxio.grpc.job.Status status = 4;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override public boolean hasStatus() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .alluxio.grpc.job.Status status = 4;</code>
   * @return The status.
   */
  @java.lang.Override public alluxio.grpc.Status getStatus() {
    @SuppressWarnings("deprecation")
    alluxio.grpc.Status result = alluxio.grpc.Status.valueOf(status_);
    return result == null ? alluxio.grpc.Status.UNKNOWN : result;
  }

  public static final int SUBMISSIONTIME_FIELD_NUMBER = 5;
  private long submissionTime_;
  /**
   * <code>optional int64 submissionTime = 5;</code>
   * @return Whether the submissionTime field is set.
   */
  @java.lang.Override
  public boolean hasSubmissionTime() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int64 submissionTime = 5;</code>
   * @return The submissionTime.
   */
  @java.lang.Override
  public long getSubmissionTime() {
    return submissionTime_;
  }

  public static final int DURATION_FIELD_NUMBER = 6;
  private long duration_;
  /**
   * <code>optional int64 duration = 6;</code>
   * @return Whether the duration field is set.
   */
  @java.lang.Override
  public boolean hasDuration() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int64 duration = 6;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }

  public static final int ERRORMESSAGE_FIELD_NUMBER = 7;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>optional string errorMessage = 7;</code>
   * @return Whether the errorMessage field is set.
   */
  @java.lang.Override
  public boolean hasErrorMessage() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string errorMessage = 7;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        errorMessage_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string errorMessage = 7;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CMDPROGRESS_FIELD_NUMBER = 8;
  private alluxio.grpc.CmdProgress cmdProgress_;
  /**
   * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
   * @return Whether the cmdProgress field is set.
   */
  @java.lang.Override
  public boolean hasCmdProgress() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
   * @return The cmdProgress.
   */
  @java.lang.Override
  public alluxio.grpc.CmdProgress getCmdProgress() {
    return cmdProgress_ == null ? alluxio.grpc.CmdProgress.getDefaultInstance() : cmdProgress_;
  }
  /**
   * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
   */
  @java.lang.Override
  public alluxio.grpc.CmdProgressOrBuilder getCmdProgressOrBuilder() {
    return cmdProgress_ == null ? alluxio.grpc.CmdProgress.getDefaultInstance() : cmdProgress_;
  }

  public static final int PROGRESSPERCENTAGE_FIELD_NUMBER = 9;
  private float progressPercentage_;
  /**
   * <code>optional float progressPercentage = 9;</code>
   * @return Whether the progressPercentage field is set.
   */
  @java.lang.Override
  public boolean hasProgressPercentage() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional float progressPercentage = 9;</code>
   * @return The progressPercentage.
   */
  @java.lang.Override
  public float getProgressPercentage() {
    return progressPercentage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, jobControlId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, operationType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, jobSource_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, status_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(5, submissionTime_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt64(6, duration_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, errorMessage_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(8, getCmdProgress());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeFloat(9, progressPercentage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, jobControlId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, operationType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, jobSource_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, submissionTime_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, duration_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, errorMessage_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getCmdProgress());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(9, progressPercentage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof alluxio.grpc.CmdSummary)) {
      return super.equals(obj);
    }
    alluxio.grpc.CmdSummary other = (alluxio.grpc.CmdSummary) obj;

    if (hasJobControlId() != other.hasJobControlId()) return false;
    if (hasJobControlId()) {
      if (getJobControlId()
          != other.getJobControlId()) return false;
    }
    if (hasOperationType() != other.hasOperationType()) return false;
    if (hasOperationType()) {
      if (operationType_ != other.operationType_) return false;
    }
    if (hasJobSource() != other.hasJobSource()) return false;
    if (hasJobSource()) {
      if (jobSource_ != other.jobSource_) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (status_ != other.status_) return false;
    }
    if (hasSubmissionTime() != other.hasSubmissionTime()) return false;
    if (hasSubmissionTime()) {
      if (getSubmissionTime()
          != other.getSubmissionTime()) return false;
    }
    if (hasDuration() != other.hasDuration()) return false;
    if (hasDuration()) {
      if (getDuration()
          != other.getDuration()) return false;
    }
    if (hasErrorMessage() != other.hasErrorMessage()) return false;
    if (hasErrorMessage()) {
      if (!getErrorMessage()
          .equals(other.getErrorMessage())) return false;
    }
    if (hasCmdProgress() != other.hasCmdProgress()) return false;
    if (hasCmdProgress()) {
      if (!getCmdProgress()
          .equals(other.getCmdProgress())) return false;
    }
    if (hasProgressPercentage() != other.hasProgressPercentage()) return false;
    if (hasProgressPercentage()) {
      if (java.lang.Float.floatToIntBits(getProgressPercentage())
          != java.lang.Float.floatToIntBits(
              other.getProgressPercentage())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasJobControlId()) {
      hash = (37 * hash) + JOBCONTROLID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getJobControlId());
    }
    if (hasOperationType()) {
      hash = (37 * hash) + OPERATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + operationType_;
    }
    if (hasJobSource()) {
      hash = (37 * hash) + JOBSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + jobSource_;
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
    }
    if (hasSubmissionTime()) {
      hash = (37 * hash) + SUBMISSIONTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSubmissionTime());
    }
    if (hasDuration()) {
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDuration());
    }
    if (hasErrorMessage()) {
      hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
    }
    if (hasCmdProgress()) {
      hash = (37 * hash) + CMDPROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getCmdProgress().hashCode();
    }
    if (hasProgressPercentage()) {
      hash = (37 * hash) + PROGRESSPERCENTAGE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getProgressPercentage());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static alluxio.grpc.CmdSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.CmdSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.CmdSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static alluxio.grpc.CmdSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static alluxio.grpc.CmdSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alluxio.grpc.CmdSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(alluxio.grpc.CmdSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alluxio.grpc.job.CmdSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alluxio.grpc.job.CmdSummary)
      alluxio.grpc.CmdSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alluxio.grpc.JobMasterProto.internal_static_alluxio_grpc_job_CmdSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alluxio.grpc.JobMasterProto.internal_static_alluxio_grpc_job_CmdSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alluxio.grpc.CmdSummary.class, alluxio.grpc.CmdSummary.Builder.class);
    }

    // Construct using alluxio.grpc.CmdSummary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCmdProgressFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      jobControlId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      operationType_ = 1;
      bitField0_ = (bitField0_ & ~0x00000002);
      jobSource_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      submissionTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      duration_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      errorMessage_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      if (cmdProgressBuilder_ == null) {
        cmdProgress_ = null;
      } else {
        cmdProgressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      progressPercentage_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return alluxio.grpc.JobMasterProto.internal_static_alluxio_grpc_job_CmdSummary_descriptor;
    }

    @java.lang.Override
    public alluxio.grpc.CmdSummary getDefaultInstanceForType() {
      return alluxio.grpc.CmdSummary.getDefaultInstance();
    }

    @java.lang.Override
    public alluxio.grpc.CmdSummary build() {
      alluxio.grpc.CmdSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public alluxio.grpc.CmdSummary buildPartial() {
      alluxio.grpc.CmdSummary result = new alluxio.grpc.CmdSummary(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jobControlId_ = jobControlId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.operationType_ = operationType_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.jobSource_ = jobSource_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.submissionTime_ = submissionTime_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.duration_ = duration_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.errorMessage_ = errorMessage_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        if (cmdProgressBuilder_ == null) {
          result.cmdProgress_ = cmdProgress_;
        } else {
          result.cmdProgress_ = cmdProgressBuilder_.build();
        }
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.progressPercentage_ = progressPercentage_;
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof alluxio.grpc.CmdSummary) {
        return mergeFrom((alluxio.grpc.CmdSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(alluxio.grpc.CmdSummary other) {
      if (other == alluxio.grpc.CmdSummary.getDefaultInstance()) return this;
      if (other.hasJobControlId()) {
        setJobControlId(other.getJobControlId());
      }
      if (other.hasOperationType()) {
        setOperationType(other.getOperationType());
      }
      if (other.hasJobSource()) {
        setJobSource(other.getJobSource());
      }
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasSubmissionTime()) {
        setSubmissionTime(other.getSubmissionTime());
      }
      if (other.hasDuration()) {
        setDuration(other.getDuration());
      }
      if (other.hasErrorMessage()) {
        bitField0_ |= 0x00000040;
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.hasCmdProgress()) {
        mergeCmdProgress(other.getCmdProgress());
      }
      if (other.hasProgressPercentage()) {
        setProgressPercentage(other.getProgressPercentage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      alluxio.grpc.CmdSummary parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (alluxio.grpc.CmdSummary) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long jobControlId_ ;
    /**
     * <code>optional int64 jobControlId = 1;</code>
     * @return Whether the jobControlId field is set.
     */
    @java.lang.Override
    public boolean hasJobControlId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 jobControlId = 1;</code>
     * @return The jobControlId.
     */
    @java.lang.Override
    public long getJobControlId() {
      return jobControlId_;
    }
    /**
     * <code>optional int64 jobControlId = 1;</code>
     * @param value The jobControlId to set.
     * @return This builder for chaining.
     */
    public Builder setJobControlId(long value) {
      bitField0_ |= 0x00000001;
      jobControlId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 jobControlId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobControlId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      jobControlId_ = 0L;
      onChanged();
      return this;
    }

    private int operationType_ = 1;
    /**
     * <code>optional .alluxio.grpc.job.OperationType operationType = 2;</code>
     * @return Whether the operationType field is set.
     */
    @java.lang.Override public boolean hasOperationType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .alluxio.grpc.job.OperationType operationType = 2;</code>
     * @return The operationType.
     */
    @java.lang.Override
    public alluxio.grpc.OperationType getOperationType() {
      @SuppressWarnings("deprecation")
      alluxio.grpc.OperationType result = alluxio.grpc.OperationType.valueOf(operationType_);
      return result == null ? alluxio.grpc.OperationType.DIST_LOAD : result;
    }
    /**
     * <code>optional .alluxio.grpc.job.OperationType operationType = 2;</code>
     * @param value The operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationType(alluxio.grpc.OperationType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      operationType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.OperationType operationType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      operationType_ = 1;
      onChanged();
      return this;
    }

    private int jobSource_ = 0;
    /**
     * <code>optional .alluxio.grpc.job.JobSource jobSource = 3;</code>
     * @return Whether the jobSource field is set.
     */
    @java.lang.Override public boolean hasJobSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .alluxio.grpc.job.JobSource jobSource = 3;</code>
     * @return The jobSource.
     */
    @java.lang.Override
    public alluxio.grpc.JobSource getJobSource() {
      @SuppressWarnings("deprecation")
      alluxio.grpc.JobSource result = alluxio.grpc.JobSource.valueOf(jobSource_);
      return result == null ? alluxio.grpc.JobSource.UNSUPPORTED : result;
    }
    /**
     * <code>optional .alluxio.grpc.job.JobSource jobSource = 3;</code>
     * @param value The jobSource to set.
     * @return This builder for chaining.
     */
    public Builder setJobSource(alluxio.grpc.JobSource value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      jobSource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.JobSource jobSource = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobSource() {
      bitField0_ = (bitField0_ & ~0x00000004);
      jobSource_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .alluxio.grpc.job.Status status = 4;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .alluxio.grpc.job.Status status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public alluxio.grpc.Status getStatus() {
      @SuppressWarnings("deprecation")
      alluxio.grpc.Status result = alluxio.grpc.Status.valueOf(status_);
      return result == null ? alluxio.grpc.Status.UNKNOWN : result;
    }
    /**
     * <code>optional .alluxio.grpc.job.Status status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(alluxio.grpc.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.Status status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = 0;
      onChanged();
      return this;
    }

    private long submissionTime_ ;
    /**
     * <code>optional int64 submissionTime = 5;</code>
     * @return Whether the submissionTime field is set.
     */
    @java.lang.Override
    public boolean hasSubmissionTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 submissionTime = 5;</code>
     * @return The submissionTime.
     */
    @java.lang.Override
    public long getSubmissionTime() {
      return submissionTime_;
    }
    /**
     * <code>optional int64 submissionTime = 5;</code>
     * @param value The submissionTime to set.
     * @return This builder for chaining.
     */
    public Builder setSubmissionTime(long value) {
      bitField0_ |= 0x00000010;
      submissionTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 submissionTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubmissionTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      submissionTime_ = 0L;
      onChanged();
      return this;
    }

    private long duration_ ;
    /**
     * <code>optional int64 duration = 6;</code>
     * @return Whether the duration field is set.
     */
    @java.lang.Override
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 duration = 6;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return duration_;
    }
    /**
     * <code>optional int64 duration = 6;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {
      bitField0_ |= 0x00000020;
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 duration = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      duration_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>optional string errorMessage = 7;</code>
     * @return Whether the errorMessage field is set.
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string errorMessage = 7;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errorMessage = 7;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errorMessage = 7;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMessage = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      bitField0_ = (bitField0_ & ~0x00000040);
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMessage = 7;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      errorMessage_ = value;
      onChanged();
      return this;
    }

    private alluxio.grpc.CmdProgress cmdProgress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        alluxio.grpc.CmdProgress, alluxio.grpc.CmdProgress.Builder, alluxio.grpc.CmdProgressOrBuilder> cmdProgressBuilder_;
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     * @return Whether the cmdProgress field is set.
     */
    public boolean hasCmdProgress() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     * @return The cmdProgress.
     */
    public alluxio.grpc.CmdProgress getCmdProgress() {
      if (cmdProgressBuilder_ == null) {
        return cmdProgress_ == null ? alluxio.grpc.CmdProgress.getDefaultInstance() : cmdProgress_;
      } else {
        return cmdProgressBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    public Builder setCmdProgress(alluxio.grpc.CmdProgress value) {
      if (cmdProgressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cmdProgress_ = value;
        onChanged();
      } else {
        cmdProgressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    public Builder setCmdProgress(
        alluxio.grpc.CmdProgress.Builder builderForValue) {
      if (cmdProgressBuilder_ == null) {
        cmdProgress_ = builderForValue.build();
        onChanged();
      } else {
        cmdProgressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    public Builder mergeCmdProgress(alluxio.grpc.CmdProgress value) {
      if (cmdProgressBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
            cmdProgress_ != null &&
            cmdProgress_ != alluxio.grpc.CmdProgress.getDefaultInstance()) {
          cmdProgress_ =
            alluxio.grpc.CmdProgress.newBuilder(cmdProgress_).mergeFrom(value).buildPartial();
        } else {
          cmdProgress_ = value;
        }
        onChanged();
      } else {
        cmdProgressBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    public Builder clearCmdProgress() {
      if (cmdProgressBuilder_ == null) {
        cmdProgress_ = null;
        onChanged();
      } else {
        cmdProgressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    public alluxio.grpc.CmdProgress.Builder getCmdProgressBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getCmdProgressFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    public alluxio.grpc.CmdProgressOrBuilder getCmdProgressOrBuilder() {
      if (cmdProgressBuilder_ != null) {
        return cmdProgressBuilder_.getMessageOrBuilder();
      } else {
        return cmdProgress_ == null ?
            alluxio.grpc.CmdProgress.getDefaultInstance() : cmdProgress_;
      }
    }
    /**
     * <code>optional .alluxio.grpc.job.CmdProgress cmdProgress = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        alluxio.grpc.CmdProgress, alluxio.grpc.CmdProgress.Builder, alluxio.grpc.CmdProgressOrBuilder> 
        getCmdProgressFieldBuilder() {
      if (cmdProgressBuilder_ == null) {
        cmdProgressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            alluxio.grpc.CmdProgress, alluxio.grpc.CmdProgress.Builder, alluxio.grpc.CmdProgressOrBuilder>(
                getCmdProgress(),
                getParentForChildren(),
                isClean());
        cmdProgress_ = null;
      }
      return cmdProgressBuilder_;
    }

    private float progressPercentage_ ;
    /**
     * <code>optional float progressPercentage = 9;</code>
     * @return Whether the progressPercentage field is set.
     */
    @java.lang.Override
    public boolean hasProgressPercentage() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional float progressPercentage = 9;</code>
     * @return The progressPercentage.
     */
    @java.lang.Override
    public float getProgressPercentage() {
      return progressPercentage_;
    }
    /**
     * <code>optional float progressPercentage = 9;</code>
     * @param value The progressPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setProgressPercentage(float value) {
      bitField0_ |= 0x00000100;
      progressPercentage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float progressPercentage = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgressPercentage() {
      bitField0_ = (bitField0_ & ~0x00000100);
      progressPercentage_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alluxio.grpc.job.CmdSummary)
  }

  // @@protoc_insertion_point(class_scope:alluxio.grpc.job.CmdSummary)
  private static final alluxio.grpc.CmdSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new alluxio.grpc.CmdSummary();
  }

  public static alluxio.grpc.CmdSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<CmdSummary>
      PARSER = new com.google.protobuf.AbstractParser<CmdSummary>() {
    @java.lang.Override
    public CmdSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CmdSummary(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CmdSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CmdSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public alluxio.grpc.CmdSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

