// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/journal_master.proto

package alluxio.grpc;

public interface GetTransferLeaderMessagePRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.journal.GetTransferLeaderMessagePRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string transferId = 1;</code>
   * @return Whether the transferId field is set.
   */
  boolean hasTransferId();
  /**
   * <code>required string transferId = 1;</code>
   * @return The transferId.
   */
  java.lang.String getTransferId();
  /**
   * <code>required string transferId = 1;</code>
   * @return The bytes for transferId.
   */
  com.google.protobuf.ByteString
      getTransferIdBytes();
}
