// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/job_master.proto

package alluxio.grpc;

public interface ListAllPOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.job.ListAllPOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .alluxio.grpc.job.Status status = 1;</code>
   * @return A list containing the status.
   */
  java.util.List<alluxio.grpc.Status> getStatusList();
  /**
   * <code>repeated .alluxio.grpc.job.Status status = 1;</code>
   * @return The count of status.
   */
  int getStatusCount();
  /**
   * <code>repeated .alluxio.grpc.job.Status status = 1;</code>
   * @param index The index of the element to return.
   * @return The status at the given index.
   */
  alluxio.grpc.Status getStatus(int index);

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional bool jobIdOnly = 3;</code>
   * @return Whether the jobIdOnly field is set.
   */
  boolean hasJobIdOnly();
  /**
   * <code>optional bool jobIdOnly = 3;</code>
   * @return The jobIdOnly.
   */
  boolean getJobIdOnly();
}
