package alluxio.master.file.metasync;

public enum SyncFailReason {
  UNKNOWN,
  UNSUPPORTED,

  LOADING_UFS_IO_FAILURE,

  PROCESSING_UNKNOWN,
  PROCESSING_CONCURRENT_UPDATE_DURING_SYNC,
  PROCESSING_FILE_DOES_NOT_EXIST,
}
