#!/bin/bash

CALLING_DIR="$(pwd)"
UNPACK_DIR="${CALLING_DIR}/unpacked"

if [[ $# -ne 1 ]]; then
    echo "Please call with the jar to unpack, e.g. ./update AlluxioCodeStyle.jar" 
    exit 1
fi

if [[ ! -d "${UNPACK_DIR}" ]]; then
  mkdir "${UNPACK_DIR}"
fi


cd "${UNPACK_DIR}"

jar -xvf "${CALLING_DIR}/$1"
cp -rf "${UNPACK_DIR}/codestyles" "${CALLING_DIR}"
cp -rf "${UNPACK_DIR}/options" "${CALLING_DIR}"
cd "${CALLING_DIR}"
rm -rf "${UNPACK_DIR}"
echo "Local files updated. Please run git commit and git push to push these updates to your Git repository."
