// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/table/table_master.proto

package alluxio.grpc.table;

public interface RangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.table.Range)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .alluxio.grpc.table.Value low = 1;</code>
   * @return Whether the low field is set.
   */
  boolean hasLow();
  /**
   * <code>optional .alluxio.grpc.table.Value low = 1;</code>
   * @return The low.
   */
  alluxio.grpc.table.Value getLow();
  /**
   * <code>optional .alluxio.grpc.table.Value low = 1;</code>
   */
  alluxio.grpc.table.ValueOrBuilder getLowOrBuilder();

  /**
   * <code>optional .alluxio.grpc.table.Value high = 2;</code>
   * @return Whether the high field is set.
   */
  boolean hasHigh();
  /**
   * <code>optional .alluxio.grpc.table.Value high = 2;</code>
   * @return The high.
   */
  alluxio.grpc.table.Value getHigh();
  /**
   * <code>optional .alluxio.grpc.table.Value high = 2;</code>
   */
  alluxio.grpc.table.ValueOrBuilder getHighOrBuilder();
}
