#!/bin/bash

SCRIPT_DIR=$(cd "$( dirname "$( readlink "$0" || echo "$0" )" )"; pwd)

(cd ${SCRIPT_DIR}/src/alluxio.org/ && GO111MODULE=on go build -o buildDistribution "build-distribution/main.go")

${SCRIPT_DIR}/src/alluxio.org/buildDistribution $@

rm ${SCRIPT_DIR}/src/alluxio.org/buildDistribution
