#!/bin/bash

SCRIPT_DIR=$(cd "$( dirname "$( readlink "$0" || echo "$0" )" )"; pwd)

(cd ${SCRIPT_DIR}/src/alluxio.org/build-distribution && go build -o buildDistribution "main.go")

${SCRIPT_DIR}/src/alluxio.org/build-distribution/buildDistribution $@

rm ${SCRIPT_DIR}/src/alluxio.org/build-distribution/buildDistribution
