#!/usr/bin/env bash

set -e

VARIABLES="\
ALLUXIO_MASTER_BIND_HOST \
ALLUXIO_MASTER_WEB_BIND_HOST \
ALLUXIO_WORKER_BIND_HOST \
ALLUXIO_WORKER_DATA_BIND_HOST \
ALLUXIO_WORKER_WEB_BIND_HOST \
ALLUXIO_MASTER_HOSTNAME \
ALLUXIO_MASTER_WEB_HOSTNAME \
ALLUXIO_WORKER_HOSTNAME \
ALLUXIO_WORKER_DATA_HOSTNAME \
ALLUXIO_WORKER_WEB_HOSTNAME"

for var in ${VARIABLES}; do
  sed -i "s/# ${var}/${var}/g" /alluxio/conf/alluxio-env.sh
done
