#!/usr/bin/env bash

set -e

VARIABLES="\
TACHYON_MASTER_BIND_HOST \
TACHYON_MASTER_WEB_BIND_HOST \
TACHYON_WORKER_BIND_HOST \
TACHYON_WORKER_DATA_BIND_HOST \
TACHYON_WORKER_WEB_BIND_HOST \
TACHYON_MASTER_HOSTNAME \
TACHYON_MASTER_WEB_HOSTNAME \
TACHYON_WORKER_HOSTNAME \
TACHYON_WORKER_DATA_HOSTNAME \
TACHYON_WORKER_WEB_HOSTNAME"

for var in ${VARIABLES}; do
  sed -i "s/# ${var}/${var}/g" /tachyon/conf/tachyon-env.sh
done
