#!/bin/bash

tachyon_dirs=$(ls -d tachyon*)
echo $tachyon_dirs
dir_list=("$tachyon_dirs")

# NOTE: the order matters but this is the right one
for i in ${dir_list[@]}; do
	echo building $i;
	cd $i;
	cat build;
	. build;
	cd ..;
done
