#!/usr/bin/env bash
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

LAUNCHER=
# If debugging is enabled propagate that through to sub-shells
if [[ "$-" == *x* ]]; then
  LAUNCHER="bash -x"
fi
CHECKER=$(cd "$( dirname "$( readlink "$0" || echo "$0" )" )"; pwd)

USAGE="Usage: checkIntegration FRAMEWORK [FRAMEWORK_ARGS]
Where FRAMEWORK is one of:
  Spark           \Run Spark job to check Spark with Alluxio integration.
  MapReduce       \Run MapReduce job to check MapReduce with Alluxio integration.
  HBase           \Run HBase job to check HBase with Alluxio integration.
  Hive            \Run Hive job to check Hive with Alluxio integration.

-h  display this help."

function run_spark() {
   ${LAUNCHER} "${CHECKER}/spark-integration.sh" "$@"
}

function run_mapreduce() {
  ${LAUNCHER} "${CHECKER}/mapreduce-integration.sh" "$@"
}

function run_hbase() {
  ${LAUNCHER} "${CHECKER}/hbase-integration.sh" "$@"
}

function run_hive() {
  ${LAUNCHER} "${CHECKER}/hive-integration.sh" "$@"
}

function main {
  case "$1" in
    SPARK | Spark | spark)
      run_spark "${@:2}"
      ;;
    MAPREDUCE | MapReduce | mapreduce)
      run_mapreduce "${@:2}"
      ;;
    HBASE | HBase | hbase)
      run_hbase "${@:2}"
      ;;
    HIVE | Hive | hive)
      run_hive "${@:2}"
      ;;
    *)
    echo -e "${USAGE}" >&2
    exit 1
  esac
}

main "$@"
