// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/catalog/catalog_master.proto

package alluxio.grpc.catalog;

public interface GetTablePResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.catalog.GetTablePResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .alluxio.grpc.catalog.TableInfo table_info = 1;</code>
   */
  boolean hasTableInfo();
  /**
   * <code>optional .alluxio.grpc.catalog.TableInfo table_info = 1;</code>
   */
  alluxio.grpc.catalog.TableInfo getTableInfo();
  /**
   * <code>optional .alluxio.grpc.catalog.TableInfo table_info = 1;</code>
   */
  alluxio.grpc.catalog.TableInfoOrBuilder getTableInfoOrBuilder();
}
