// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/catalog/catalog_master.proto

package alluxio.grpc.catalog;

public interface TableInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.catalog.TableInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string table_name = 1;</code>
   */
  boolean hasTableName();
  /**
   * <code>optional string table_name = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>optional string table_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>optional string db_name = 2;</code>
   */
  boolean hasDbName();
  /**
   * <code>optional string db_name = 2;</code>
   */
  java.lang.String getDbName();
  /**
   * <code>optional string db_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getDbNameBytes();

  /**
   * <code>optional .alluxio.grpc.catalog.TableInfo.TableType type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>optional .alluxio.grpc.catalog.TableInfo.TableType type = 3;</code>
   */
  alluxio.grpc.catalog.TableInfo.TableType getType();

  /**
   * <code>optional uint32 version = 4;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional uint32 version = 4;</code>
   */
  int getVersion();

  /**
   * <code>optional .alluxio.grpc.catalog.Schema schema = 5;</code>
   */
  boolean hasSchema();
  /**
   * <code>optional .alluxio.grpc.catalog.Schema schema = 5;</code>
   */
  alluxio.grpc.catalog.Schema getSchema();
  /**
   * <code>optional .alluxio.grpc.catalog.Schema schema = 5;</code>
   */
  alluxio.grpc.catalog.SchemaOrBuilder getSchemaOrBuilder();

  /**
   * <code>optional .alluxio.grpc.catalog.UdbTableInfo udb_info = 6;</code>
   */
  boolean hasUdbInfo();
  /**
   * <code>optional .alluxio.grpc.catalog.UdbTableInfo udb_info = 6;</code>
   */
  alluxio.grpc.catalog.UdbTableInfo getUdbInfo();
  /**
   * <code>optional .alluxio.grpc.catalog.UdbTableInfo udb_info = 6;</code>
   */
  alluxio.grpc.catalog.UdbTableInfoOrBuilder getUdbInfoOrBuilder();
}
