/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package tachyon.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Command implements org.apache.thrift.TBase<Command, Command._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Command");

  private static final org.apache.thrift.protocol.TField M_COMMAND_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("mCommandType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField M_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("mData", org.apache.thrift.protocol.TType.LIST, (short)2);

  /**
   * 
   * @see CommandType
   */
  public CommandType mCommandType; // required
  public List<Long> mData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see CommandType
     */
    M_COMMAND_TYPE((short)1, "mCommandType"),
    M_DATA((short)2, "mData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // M_COMMAND_TYPE
          return M_COMMAND_TYPE;
        case 2: // M_DATA
          return M_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.M_COMMAND_TYPE, new org.apache.thrift.meta_data.FieldMetaData("mCommandType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, CommandType.class)));
    tmpMap.put(_Fields.M_DATA, new org.apache.thrift.meta_data.FieldMetaData("mData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Command.class, metaDataMap);
  }

  public Command() {
  }

  public Command(
    CommandType mCommandType,
    List<Long> mData)
  {
    this();
    this.mCommandType = mCommandType;
    this.mData = mData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Command(Command other) {
    if (other.isSetMCommandType()) {
      this.mCommandType = other.mCommandType;
    }
    if (other.isSetMData()) {
      List<Long> __this__mData = new ArrayList<Long>();
      for (Long other_element : other.mData) {
        __this__mData.add(other_element);
      }
      this.mData = __this__mData;
    }
  }

  public Command deepCopy() {
    return new Command(this);
  }

  @Override
  public void clear() {
    this.mCommandType = null;
    this.mData = null;
  }

  /**
   * 
   * @see CommandType
   */
  public CommandType getMCommandType() {
    return this.mCommandType;
  }

  /**
   * 
   * @see CommandType
   */
  public Command setMCommandType(CommandType mCommandType) {
    this.mCommandType = mCommandType;
    return this;
  }

  public void unsetMCommandType() {
    this.mCommandType = null;
  }

  /** Returns true if field mCommandType is set (has been assigned a value) and false otherwise */
  public boolean isSetMCommandType() {
    return this.mCommandType != null;
  }

  public void setMCommandTypeIsSet(boolean value) {
    if (!value) {
      this.mCommandType = null;
    }
  }

  public int getMDataSize() {
    return (this.mData == null) ? 0 : this.mData.size();
  }

  public java.util.Iterator<Long> getMDataIterator() {
    return (this.mData == null) ? null : this.mData.iterator();
  }

  public void addToMData(long elem) {
    if (this.mData == null) {
      this.mData = new ArrayList<Long>();
    }
    this.mData.add(elem);
  }

  public List<Long> getMData() {
    return this.mData;
  }

  public Command setMData(List<Long> mData) {
    this.mData = mData;
    return this;
  }

  public void unsetMData() {
    this.mData = null;
  }

  /** Returns true if field mData is set (has been assigned a value) and false otherwise */
  public boolean isSetMData() {
    return this.mData != null;
  }

  public void setMDataIsSet(boolean value) {
    if (!value) {
      this.mData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case M_COMMAND_TYPE:
      if (value == null) {
        unsetMCommandType();
      } else {
        setMCommandType((CommandType)value);
      }
      break;

    case M_DATA:
      if (value == null) {
        unsetMData();
      } else {
        setMData((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case M_COMMAND_TYPE:
      return getMCommandType();

    case M_DATA:
      return getMData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case M_COMMAND_TYPE:
      return isSetMCommandType();
    case M_DATA:
      return isSetMData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Command)
      return this.equals((Command)that);
    return false;
  }

  public boolean equals(Command that) {
    if (that == null)
      return false;

    boolean this_present_mCommandType = true && this.isSetMCommandType();
    boolean that_present_mCommandType = true && that.isSetMCommandType();
    if (this_present_mCommandType || that_present_mCommandType) {
      if (!(this_present_mCommandType && that_present_mCommandType))
        return false;
      if (!this.mCommandType.equals(that.mCommandType))
        return false;
    }

    boolean this_present_mData = true && this.isSetMData();
    boolean that_present_mData = true && that.isSetMData();
    if (this_present_mData || that_present_mData) {
      if (!(this_present_mData && that_present_mData))
        return false;
      if (!this.mData.equals(that.mData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Command other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Command typedOther = (Command)other;

    lastComparison = Boolean.valueOf(isSetMCommandType()).compareTo(typedOther.isSetMCommandType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMCommandType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mCommandType, typedOther.mCommandType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMData()).compareTo(typedOther.isSetMData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mData, typedOther.mData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // M_COMMAND_TYPE
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.mCommandType = CommandType.findByValue(iprot.readI32());
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // M_DATA
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
              this.mData = new ArrayList<Long>(_list20.size);
              for (int _i21 = 0; _i21 < _list20.size; ++_i21)
              {
                long _elem22; // required
                _elem22 = iprot.readI64();
                this.mData.add(_elem22);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.mCommandType != null) {
      oprot.writeFieldBegin(M_COMMAND_TYPE_FIELD_DESC);
      oprot.writeI32(this.mCommandType.getValue());
      oprot.writeFieldEnd();
    }
    if (this.mData != null) {
      oprot.writeFieldBegin(M_DATA_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, this.mData.size()));
        for (long _iter23 : this.mData)
        {
          oprot.writeI64(_iter23);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Command(");
    boolean first = true;

    sb.append("mCommandType:");
    if (this.mCommandType == null) {
      sb.append("null");
    } else {
      sb.append(this.mCommandType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mData:");
    if (this.mData == null) {
      sb.append("null");
    } else {
      sb.append(this.mData);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

