{
 "title": "Alluxio",
 "description": "A Template dashboard for Alluxio",
 "time": { "from": "now-90m", "to": "now" },
 "panels": [
  { "title": "Alluxio Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% Free Alluxio Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(#A, #B), 100), 'Free Alluxio Space')",
     "targetFull": "alias(scale(divideSeries(Master.CapacityFree, Master.CapacityTotal), 100), 'Free Alluxio Space')"
    }
   ]
  },
  {
   "title": "Alluxio Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(Master.CapacityUsedTierMEM, 'Space Used')"
    }
   ]
  },
  { "title": "High Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bytes Served from Alluxio",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sum(Worker.*.BytesReadAlluxio.count))"
    }
   ]
  },
  {
   "title": "Total Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sum(cluster.UfsOpConnectFromMaster.*), 'Open Connections')"
    }
   ]
  },
  {
   "title": "Bytes Served from UFS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(cluster.BytesReadUfsAll)"
    }
   ]
  },
  {
   "title": "UFSes Mounted",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "refCount": 1,
     "target": "alias(offset(diffSeries(#A, #B), 1), 'UFSes')",
     "targetFull": "alias(offset(diffSeries(aliasByMetric(diffSeries(Master.MountOps.count, Master.MountFailures.*.count)), Master.UnmountOps.count), 1), 'UFSes')"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "aliasByMetric(Master.Workers)" }
   ]
  },
  { "title": "Logical Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Directories Created",
   "type": "singlestat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "Master.DirectoriesCreated.count"
    }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByMetric(Master.FilesPinned)"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByMetric(Master.TotalPaths)"
    }
   ]
  },
  {
   "title": "Complete File Operations",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.CompleteFileOps.count" }
   ]
  },
  {
   "title": "Create Directory Oprtations",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "Master.CreateDirectoryOps.count"
    }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "singlestat",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.DeletePathOps.count" }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FileInfosGot.count" }
   ]
  },
  {
   "title": "Files Freed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FilesFreed.count" }
   ]
  },
  {
   "title": "Mount Operations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.MountOps.count" }
   ]
  },
  {
   "title": "Unmount Operations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.UnmountOps.count" }
   ]
  },
  {
   "title": "Alluxio I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Read UFS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(sum(cluster.BytesReadUfsAll))"
      }
     ]
    },
    {
     "title": "Bytes Read Doman",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "alias(cluster.BytesReadDomain, 'BytesReadDoman')"
      }
     ]
    },
    {
     "title": "Bytes Read Local",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(cluster.BytesReadLocal)"
      }
     ]
    },
    {
     "title": "Bytes Written Doman",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(cluster.BytesWrittenDomain)"
      }
     ]
    },
    {
     "title": "Bytes Written UFS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(cluster.BytesWrittenUfsAll)"
      }
     ]
    }
   ]
  },
  {
   "title": "Alluxio Metadata Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Heart Beat",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(Master.blockHeartbeat.*.p50, 'p50')"
      },
      {
       "target": "alias(Master.blockHeartbeat.*.p95, 'p95')"
      },
      {
       "target": "alias(Master.blockHeartbeat.*.p99, 'p99')"
      }
     ]
    },
    {
     "title": "Get Config Hash",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(Master.getConfigHash.User:root.p50)"
      },
      {
       "target": "aliasByMetric(Master.getConfigHash.User:root.p95)"
      },
      {
       "target": "aliasByMetric(Master.getConfigHash.User:root.p99)"
      }
     ]
    },
    {
     "title": "Get Configuration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(Master.getConfiguration.*.p50)"
      },
      {
       "target": "aliasByMetric(Master.getConfiguration.*.p95)"
      },
      {
       "target": "aliasByMetric(Master.getConfiguration.*.p99)"
      }
     ]
    },
    {
     "title": "Get Pinned Fields",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(Master.getPinnedFileIds.*.p50)"
      },
      {
       "target": "aliasByMetric(Master.getPinnedFileIds.*.p95)"
      },
      {
       "target": "aliasByMetric(Master.getPinnedFileIds.*.p99)"
      }
     ]
    },
    {
     "title": "Worker Heartbeat",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(Master.workerHeartbeat.*.p50)"
      },
      {
       "target": "aliasByMetric(Master.workerHeartbeat.*.p95)"
      },
      {
       "target": "aliasByMetric(Master.workerHeartbeat.*.p99)"
      }
     ]
    }
   ]
  },
  {
   "title": "UFS Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Space Invocations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "Master.GetSpace.*.*.count" }
     ]
    },
    {
     "title": "Get Status Invocations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "target": "Master.GetStatus.*.count" }
     ]
    },
    {
     "title": "Get Space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(Master.GetSpace.*.*.p50)"
      },
      {
       "target": "aliasByMetric(Master.GetSpace.*.*.p95)"
      },
      {
       "target": "aliasByMetric(Master.GetSpace.*.*.p99)"
      }
     ]
    },
    {
     "title": "Get Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(Master.GetStatus.*.p50)"
      },
      {
       "target": "aliasByMetric(Master.GetStatus.*.p95)"
      },
      {
       "target": "aliasByMetric(Master.GetStatus.*.p99)"
      }
     ]
    }
   ]
  }
 ]
}