{
 "title": "Alluxio Master(Graphite)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "total.used" }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "Master.CapacityUsed" }
   ]
  },
  {
   "title": "Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.Workers" }
   ]
  },
  {
   "title": "Total Paths",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "Master.TotalPaths" }
   ]
  },
  {
   "title": "Files Freed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FilesFreed.count" }
   ]
  },
  {
   "title": "New Block Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.GetNewBlockOps.count" }
   ]
  },
  {
   "title": "Files Completed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FilesCompleted.count" }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.DeletePathOps.count" }
   ]
  },
  {
   "title": "Directories Created",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "Master.DirectoriesCreated.count"
    }
   ]
  },
  {
   "title": "Set Attribute Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.SetAttributeOps.count" }
   ]
  },
  {
   "title": "Files Persisted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FilesPersisted.count" }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FilesPinned" }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.FileInfosGot.count" }
   ]
  },
  {
   "title": "Paths Mounted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Master.PathsMounted.count" }
   ]
  },
  {
   "title": "UFS Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "Master.UfsCapacityFree" },
    { "target": "Master.UfsCapacityTotal" },
    { "target": "Master.UfsCapacityUsed" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "heap.used" }
   ]
  },
  {
   "title": "Code Cache Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "pools.Code-Cache.used" }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "non-heap.used" }
   ]
  }
 ]
}