{
 "title": "Alluxio Master(Prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UFS Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "Master_UfsCapacityFree{job=\"alluxio master\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "Master_UfsCapacityTotal{job=\"alluxio master\"}",
     "legendFormat": "total"
    },
    {
     "expr": "Master_UfsCapacityUsed{job=\"alluxio master\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "Master_CapacityUsed{job=\"alluxio master\"}",
     "legendFormat": "Used Capacity"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_Workers{job=\"alluxio master\"}",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_TotalPaths{job=\"alluxio master\"}",
     "legendFormat": "Total Paths"
    }
   ]
  },
  {
   "title": "Files Freed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_FilesFreed{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "New Block Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_GetNewBlockOps{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Files Completed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_FilesCompleted{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_DeletePathOps{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Directories Created",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_DirectoriesCreated{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Set Attribute Operations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_SetAttributeOps{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Files Persisted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_FilesPersisted{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "Master_FilesPinned" }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_FileInfosGot{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Paths Mounted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Master_MountOps{job=\"alluxio master\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "total_used{job='alluxio master'}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "heap_used{job=\"alluxio master\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "pools_Code_Cache_used{job=\"alluxio master\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "non_heap_used{job=\"alluxio master\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}